# RULE-DEV:r17 GCS r17's file prolog is a C block comment, which Python cannot carry. The module
# docstring below holds the same information in the form the language allows.
"""The mechanical half of GCS v1.1.4, run over src/ and tests/ -- decision D11's validator.

    python tests/validate_gcs.py                       src/ and tests/, which is what CI runs
    python tests/validate_gcs.py src/Ir.h tests/unit   only what is named, inside the same scope
    python tests/validate_gcs.py --format              and clang-format 18.1.3 must be a no-op
    python tests/validate_gcs.py --format --clang-format <path>   that clang-format, not the one on PATH
    python tests/validate_gcs.py --self-test           every rule but tc1 shown firing on a known-bad input

What a machine can check without a compiler, it checks: the r17 prolog (the standard's own regexes and
its twelve fields in order), r8's three-space indent and its ban on tabs, e2's 150 and 180 columns,
tc2's CRLF, and ASCII -- the sources carry no BOM and the project does not pass /utf-8, so a non-ASCII
byte would be read in whatever code page the compiler runs under. With --format it also holds the tree
to clang-format 18.1.3, reported under tc1. Everything else stays with review: naming, the typedef
lattice, whether a comment is true.

include/ is exempt, and the exemption lives here rather than in the CI invocation so that a hand run
cannot reach a different verdict (D11). The six owner-authored headers carry a nonconforming ISA token
and two pre-r17 banners that CLAUDE.md says to report, not fix, so a path that resolves into include/ is
never judged however it is named. tests/fixtures/ is input data (.editorconfig's RULE-DEV:tc2), and
tests/build/, tests/x64/ and __pycache__/ are generated, so none of those is judged either. Any other
file under src/ or tests/ whose type this script has no rules for is a problem rather than a silent
pass, and so is a symbolic link, which Git checks out as a link on Linux and as a text file on Windows.
Paths compare in exact letter case on every host, as Git's do, so a verdict never depends on whether the
file system folds case. The Python checks use the running interpreter's grammar; CI's is 3.12.

Exit status: 0 clean; 1 at least one problem, including a default run that finds nothing to judge; 2 a
usage error, or named paths that leave nothing to judge.
"""

import copy
import datetime
import io
import os
import re
import shutil
import subprocess
import sys
import tempfile
import tokenize

ROOT = os.path.dirname(os.path.realpath(__file__))
REPO = os.path.dirname(ROOT)

USAGE = """    python tests/validate_gcs.py                       src/ and tests/, which is what CI runs
    python tests/validate_gcs.py src/Ir.h tests/unit   only what is named, inside the same scope
    python tests/validate_gcs.py --format              and clang-format 18.1.3 must be a no-op
    python tests/validate_gcs.py --format --clang-format <path>   that clang-format, not the one on PATH
    python tests/validate_gcs.py --self-test           every rule but tc1 shown firing on a known-bad input"""

# The two directories D11 names. A run with no arguments judges exactly these.
SCOPE = ("src", "tests")

# Never judged, whatever the command line says. The reason is printed when a named path lands here.
EXEMPT = "include"
EXEMPT_REASON = "exempt under D11 -- the owner-authored headers are reported, not fixed"
SKIPPED_DIRS = {
    ("tests", "fixtures"): "fixture parts are input data, byte for byte (.editorconfig RULE-DEV:tc2)",
    ("tests", "build"): "generated by make_fixtures.py",
    ("tests", "x64"): "build output of the unit-test project",
}
SKIPPED_NAMES = {"__pycache__": "generated by CPython"}
SKIPPED_SUFFIXES = {".vcxproj.user": "Visual Studio's per-user settings"}
LINK_REASON = "a symbolic link; Git checks one out as a link on Linux and as a text file on Windows, so its verdict would depend on the host"

# What each kind of file is held to. C and C++ carry every rule. Python carries a tagged r17 deviation
# and a tagged four-space indent (.editorconfig's RULE-DEV:r8), so its prolog check is the tag itself.
# MSBuild XML is written and rewritten by Visual Studio, two-space indented, with <Import> elements of
# 179 columns it puts back on every save: r8 does not reach it and e2's "unless splitting is
# impractical" is exactly its case, so only the hard cap binds -- RULE-DEV:r8,e2 for IDE-owned XML.
CPP = "C++"
PYTHON = "Python"
MSBUILD = "MSBuild"
CLASSES = {
    ".c": CPP, ".cpp": CPP, ".h": CPP, ".hpp": CPP, ".inl": CPP,
    ".py": PYTHON,
    ".vcxproj": MSBUILD, ".filters": MSBUILD, ".props": MSBUILD,
}
TAB_ADVICE = {CPP: "indent with three spaces", PYTHON: "indent with four spaces", MSBUILD: "indent with spaces"}

SOFT_WIDTH = 150
HARD_WIDTH = 180
WIDTH_MARK = {CPP: " // WIDTH-EXEMPT", PYTHON: " # WIDTH-EXEMPT"}
PYTHON_TAG = re.compile(r"# RULE-DEV:r17 +\S")
PYTHON_STEP = 4
CPP_STEP = 3
CLANG_FORMAT_VERSION = "18.1.3"
UTF8_BOM = b"\xef\xbb\xbf"

# r17's "Validation (minimal)", verbatim from GDC_GCS_v1_1_4.md.
PROLOG_OPEN = re.compile(r"^\s*/\*\s*$")
PROLOG_CLOSE = re.compile(r"^\s*\*/\s*$")
PROLOG_INNER = re.compile(r"^ \*(| .{0,147}| .{0,161} // WIDTH-EXEMPT)$")
PROLOG_DATE = re.compile(r"^ \* (Created|Last Modified): \d{4}-\d{2}-\d{2}$")
PROLOG_VERSION = re.compile(r"^ \* Version: v\d+\.\d+(\.\d+)?$")
PROLOG_LICENSE = re.compile(r"^ \* License: [A-Za-z0-9.+-]+  Copyright: .+$")
ISA_TOKENS = ("Scalar", "SSE4.2", "AVX2", "AVX-512")
THREAD_SAFETY = ("N/A", "Reentrant", "MT-safe")

# r17's required fields, lettered A to L, in the order the standard lists them. Only these three may
# run onto a continuation line: To Do by r17's own words, and the two lists beside it.
FIELDS = ("File", "Version", "Owner", "Created", "Last Modified", "Description", "To Do", "Dependencies",
          "ISA", "Thread-safety", "Reviewers", "License")
MULTILINE = ("To Do", "Dependencies", "Reviewers")

# Every rule check_file and select can report under, so the self-test can prove each one still fires.
# The formatter's findings are reported under tc1, the rule .clang-format implements; they need the pinned
# binary, so the self-test cannot fire them and RULES does not list them.
RULES = ("r17", "r8", "e2", "tc2", "ascii", "en3", "syntax", "scope")
FORMAT_RULE = "tc1"


class UsageError(Exception):
    pass


# ---------------------------------------------------------------------------------------------------
# Choosing what to judge


def place(parts):
    """Where a repository-relative path, split on '/', sits: (kind, reason), kind being 'exempt',
    'outside', 'skip', 'case' or 'inside'. Names compare in exact case on every host, as Git's do; a
    name that matches a special one only when case is folded is 'case', because a file system that folds
    case would put it somewhere this script treats differently."""
    specials = [(0, EXEMPT)] + [(0, top) for top in SCOPE] + [(1, sub) for _, sub in SKIPPED_DIRS]
    for position, name in specials:
        if len(parts) > position and parts[position] != name and parts[position].lower() == name.lower():
            if position == 0 or parts[0] == "tests":
                return "case", "differs from %s only in letter case, so a host that folds case would treat it as %s" % (
                    "/".join(parts[:position] + [name]), name)
    for part in parts:
        for name in SKIPPED_NAMES:
            if part != name and part.lower() == name.lower():
                return "case", "differs from %s only in letter case" % name
    if parts[0] == EXEMPT:
        return "exempt", EXEMPT_REASON
    if parts[0] not in SCOPE:
        return "outside", "outside D11's scope, which is %s" % " and ".join(top + "/" for top in SCOPE)
    for prefix, reason in SKIPPED_DIRS.items():
        if tuple(parts[:len(prefix)]) == prefix:
            return "skip", reason
    for part in parts:
        if part in SKIPPED_NAMES:
            return "skip", SKIPPED_NAMES[part]
    return "inside", ""


def verdict_for(rel):
    """What happens to one repository-relative file path: (kind, reason). kind is 'judge', with the file
    class as reason, or 'skip', 'exempt', 'outside' or 'unknown', with the reason in words."""
    kind, reason = place(rel.split("/"))
    if kind == "case":
        return "unknown", reason
    if kind != "inside":
        return kind, reason
    for suffix, why in SKIPPED_SUFFIXES.items():
        if rel.endswith(suffix):
            return "skip", why
    found = CLASSES.get(os.path.splitext(rel)[1].lower())
    if found is None:
        return "unknown", "no rules are defined for this type of file; give it a class in validate_gcs.py, or move it"
    return "judge", found


class Selection:
    """What a run will judge, in order, with the problems and notes met while choosing it."""

    def __init__(self, root):
        self.root = os.path.realpath(root)
        self.files = []
        self.problems = []
        self.notes = []
        self.seen = set()

    def problem(self, rel, reason):
        if ("problem", rel) not in self.seen:
            self.seen.add(("problem", rel))
            self.problems.append((rel, 0, "scope", reason))

    def offer(self, rel):
        """Takes one repository-relative file. Returns 1 when it will be judged, else 0."""
        kind, reason = verdict_for(rel)
        if kind == "judge":
            if ("file", rel) not in self.seen:
                self.seen.add(("file", rel))
                self.files.append((rel, reason))
            return 1
        if kind == "unknown":
            self.problem(rel, reason)
        return 0

    def walk(self, top):
        """Offers every file under one repository-relative directory, sorted, pruning what is never
        judged and reporting a link or a case-variant directory rather than following it."""
        count = 0
        for here, dirs, names in os.walk(os.path.join(self.root, *top.split("/"))):
            base = os.path.relpath(here, self.root).replace(os.sep, "/")
            keep = []
            for name in sorted(dirs):
                rel = base + "/" + name
                kind, reason = place(rel.split("/"))
                if os.path.islink(os.path.join(here, name)):
                    self.problem(rel, LINK_REASON)
                elif kind == "case":
                    self.problem(rel, reason)
                elif kind == "inside":
                    keep.append(name)
            dirs[:] = keep
            for name in sorted(names):
                rel = base + "/" + name
                if os.path.islink(os.path.join(here, name)):
                    self.problem(rel, LINK_REASON)
                else:
                    count += self.offer(rel)
        return count

    def default(self):
        """src/ and tests/, and a problem for whichever of them holds nothing to judge -- a run that
        judged nothing must not read as a pass."""
        for entry in sorted(os.listdir(self.root)):
            if os.path.isdir(os.path.join(self.root, entry)) and place([entry])[0] == "case":
                self.problem(entry, place([entry])[1])
        for top in SCOPE:
            path = os.path.join(self.root, top)
            if os.path.islink(path):
                self.problem(top, LINK_REASON)
            elif not os.path.isdir(path):
                self.problem(top, "D11 names this directory and it does not exist")
            elif self.walk(top) == 0:
                self.problem(top, "nothing here to judge, and D11 names this directory")

    def name(self, name):
        """Takes one path from the command line, resolved through any link to where it really is, so a
        name that reaches include/ some other way is still exempt."""
        full = os.path.abspath(name)
        if not os.path.lexists(full):
            raise UsageError("no such file or directory: %s" % name)
        # The parent resolved, the last name kept: the link itself, however the repository was reached --
        # through another link, or on Windows through an 8.3 short name such as RUNNER~1 in %TEMP%.
        nominal = inside(os.path.join(os.path.realpath(os.path.dirname(full)), os.path.basename(full)), self.root)
        if nominal is not None and os.path.islink(full):
            self.problem(nominal, LINK_REASON)
            return
        rel = inside(os.path.realpath(full), self.root)
        if rel is None:
            raise UsageError("%s is outside the repository" % name)
        if rel == ".":
            self.notes.append("%s: the repository root, so src/ and tests/ exactly as a run with no arguments" % name)
            self.notes.append("%s/: not judged -- %s" % (EXEMPT, EXEMPT_REASON))
            self.default()
            return
        kind, reason = place(rel.split("/"))
        if kind == "case":
            self.problem(rel, reason)
        elif kind != "inside":
            self.notes.append("%s: not judged -- %s" % (rel, reason))
        elif os.path.isdir(full):
            self.walk(rel)
        else:
            kind, reason = verdict_for(rel)
            if kind in ("skip", "exempt", "outside"):
                self.notes.append("%s: not judged -- %s" % (rel, reason))
            else:
                self.offer(rel)


def inside(path, root):
    """path relative to root with forward slashes, or None when it is not under root."""
    try:
        rel = os.path.relpath(path, root).replace(os.sep, "/")
    except ValueError:
        return None
    return None if rel == ".." or rel.startswith("../") else rel


def select(args, root=REPO):
    """Turns the command line into a Selection. No arguments means src/ and tests/."""
    chosen = Selection(root)
    if not args:
        chosen.default()
    for name in args:
        chosen.name(name)
    return chosen


# ---------------------------------------------------------------------------------------------------
# Rules every file is held to


def split_lines(data):
    """Splits the bytes into lines without their terminators. Latin-1 maps each byte to one character,
    so a column is a byte; a byte that is not ASCII is the ASCII rule's to report."""
    text = data.decode("latin-1")
    lines = text.split("\n")
    if lines and lines[-1] == "":
        lines.pop()
    return [line[:-1] if line.endswith("\r") else line for line in lines]


def line_of(data, offset):
    return data.count(b"\n", 0, offset) + 1


def check_bytes(data, kind):
    """tc2's CRLF, r8's no tabs, and ASCII. Each reports its first offence and how many there are,
    because a file saved with the wrong settings breaks one of them on every line."""
    problems = []
    start = len(UTF8_BOM) if kind == MSBUILD and data.startswith(UTF8_BOM) else 0

    def report(rule, offsets, what):
        if offsets:
            more = "" if len(offsets) == 1 else " (%d in all)" % len(offsets)
            problems.append((line_of(data, offsets[0]), rule, what + more))

    report("tc2", [m.start() for m in re.finditer(rb"(?<!\r)\n", data)], "a line ends LF rather than CRLF")
    report("tc2", [m.start() for m in re.finditer(rb"\r(?!\n)", data)], "a carriage return is not followed by a line feed")
    if data and not data.endswith(b"\n"):
        problems.append((line_of(data, len(data)), "tc2", "the last line has no CRLF after it"))
    report("r8", [m.start() for m in re.finditer(rb"\t", data)], "a tab character; %s" % TAB_ADVICE[kind])
    wide = [i for i in range(start, len(data)) if data[i] > 0x7F]
    if wide:
        report("ascii", wide, "byte 0x%02X is not ASCII" % data[wide[0]])
    controls = [i for i in range(len(data)) if (data[i] < 0x20 and data[i] not in b"\t\r\n") or data[i] == 0x7F]
    if controls:
        report("ascii", controls, "control byte 0x%02X" % data[controls[0]])
    return problems


def check_width(lines, kind, inner=range(0)):
    """e2: 150 columns unless splitting is impractical, and 180 whatever. A C++ or Python line may take
    the extra thirty by saying so with r17's own WIDTH-EXEMPT mark, and a C++ line continued with a
    backslash takes them without one, because clang-format aligns every escaped newline at its 180-column
    limit (LLVM's AlignEscapedNewlines: Right) and a mark cannot follow the backslash. Project XML is
    IDE-owned and held to the hard cap alone. The prolog's inner lines are r17's to measure."""
    problems = []
    mark = WIDTH_MARK.get(kind)
    for index, line in enumerate(lines):
        if index in inner:
            continue
        width = len(line) - (3 if index == 0 and kind == MSBUILD and line.startswith("\xef\xbb\xbf") else 0)
        if width > HARD_WIDTH:
            problems.append((index + 1, "e2", "%d columns is past the hard cap of %d" % (width, HARD_WIDTH)))
        elif width > SOFT_WIDTH and mark is not None and not line.endswith(mark) and not (kind == CPP and line.endswith("\\")):
            problems.append((index + 1, "e2", "%d columns; wrap at %d, or end the line with '%s' if it cannot be split"
                             % (width, SOFT_WIDTH, mark.strip())))
    return problems


# ---------------------------------------------------------------------------------------------------
# r17: the file prolog


def check_prolog(lines, filename):
    """Returns (problems, range of the inner lines). The regexes are the standard's; the field walk is
    the rest of r17's text made mechanical: twelve fields, once each, A to L, To Do numbered 1), 2) ...
    and every continuation aligned under the value it continues."""
    problems = []
    if not lines or not PROLOG_OPEN.match(lines[0]):
        return [(1, "r17", "the file must open with the prolog's '/*' line")], range(0)
    close = next((index for index in range(1, len(lines)) if PROLOG_CLOSE.match(lines[index])), -1)
    if close < 0:
        return [(1, "r17", "the prolog's closing ' */' line was not found")], range(0)

    fields = []
    current = None
    for index in range(1, close):
        line = lines[index]
        number = index + 1
        if line == " *":
            current = None
            continue
        if line.rstrip(" ") == " *":
            # The regex lets ' * ' through as a content line of nothing; r17's prose does not.
            problems.append((number, "r17", "a blank prolog line is exactly ' *', with nothing after it"))
            current = None
            continue
        if not line.startswith(" * "):
            problems.append((number, "r17", "a prolog line starts with exactly ' * ', or is exactly ' *'"))
            current = None
            continue
        if not PROLOG_INNER.match(line):
            problems.append((number, "r17", "a prolog line is %d columns; wrap at 150, or end it with '%s' within 180"
                             % (len(line), WIDTH_MARK[CPP].strip())))
        if line.endswith(WIDTH_MARK[CPP]):
            line = line[:-len(WIDTH_MARK[CPP])]
        text = line[3:]
        if re.match(r"\s*History\s*:", text):
            problems.append((number, "r17", "no 'History:' in a prolog; history belongs in CHANGELOG.md (c1)"))
            current = None
            continue
        label = next((f for f in FIELDS if text.startswith(f + ":")), None)
        if label is not None:
            value = text[len(label) + 1:]
            if not value.startswith(" ") or value.startswith("  ") or not value.strip():
                problems.append((number, "r17", "'%s:' takes one space and then its value" % label))
            current = {"label": label, "line": number, "column": 3 + len(label) + 2, "value": value.strip(), "more": []}
            fields.append(current)
        elif text.startswith(" "):
            if current is None or current["label"] not in MULTILINE:
                what = "nothing" if current is None else "'%s:', which takes one line" % current["label"]
                problems.append((number, "r17", "a continuation line, but it continues %s" % what))
                current = None
            else:
                body = line[2:]
                current["more"].append((number, 2 + len(body) - len(body.lstrip(" ")), body.strip()))
        else:
            problems.append((number, "r17", "not one of r17's twelve fields: %s" % text.split(":")[0][:40]))
            current = None

    seen = [f["label"] for f in fields]
    for label in FIELDS:
        if seen.count(label) == 0:
            problems.append((close + 1, "r17", "the '%s:' field is missing" % label))
        elif seen.count(label) > 1:
            later = [f["line"] for f in fields if f["label"] == label][1]
            problems.append((later, "r17", "'%s:' appears %d times" % (label, seen.count(label))))
    order = [FIELDS.index(label) for label in seen]
    for position in range(1, len(order)):
        if order[position] < order[position - 1]:
            problems.append((fields[position]["line"], "r17", "'%s:' comes after '%s:'; r17 orders the fields A to L"
                             % (fields[position]["label"], fields[position - 1]["label"])))
            break

    first = {}
    for field in fields:
        first.setdefault(field["label"], field)
    for field in first.values():
        problems.extend(check_field(field, lines, filename))

    created = first.get("Created")
    modified = first.get("Last Modified")
    if created and modified:
        try:
            if datetime.date.fromisoformat(created["value"]) > datetime.date.fromisoformat(modified["value"]):
                problems.append((modified["line"], "r17", "'Last Modified:' is earlier than 'Created:'"))
        except ValueError:
            pass
    return problems, range(1, close)


def check_field(field, lines, filename):
    """One field's own rule. The full-line regexes are r17's; the rest is the field's text."""
    label = field["label"]
    value = field["value"]
    number = field["line"]
    line = lines[number - 1]
    if line.endswith(WIDTH_MARK[CPP]):
        line = line[:-len(WIDTH_MARK[CPP])]
    problems = []

    def fail(message, at=number):
        problems.append((at, "r17", message))

    if label == "File" and value != filename:
        fail("'File:' says %s, but the file is %s" % (value, filename))
    elif label == "Version" and not PROLOG_VERSION.match(line):
        fail("'Version:' is vMAJOR.MINOR or vMAJOR.MINOR.PATCH")
    elif label in ("Created", "Last Modified"):
        if not PROLOG_DATE.match(line):
            fail("'%s:' is a YYYY-MM-DD date and nothing else" % label)
        else:
            try:
                datetime.date.fromisoformat(value)
            except ValueError:
                fail("'%s:' is not a calendar date: %s" % (label, value))
    elif label == "To Do":
        item = re.match(r"(\d+)\) \S", value)
        if not item or item.group(1) != "1":
            fail("'To Do:' opens with item 1), on the label's own line")
        expected = 2
        text_column = field["column"] + len("1) ")
        for at, column, content in field["more"]:
            numbered = re.match(r"(\d+)\) \S", content)
            if column == field["column"] and numbered:
                if int(numbered.group(1)) != expected:
                    fail("To Do item %s) should be %d)" % (numbered.group(1), expected), at)
                expected = int(numbered.group(1)) + 1
                text_column = column + len(numbered.group(1)) + 2
            elif column == field["column"]:
                fail("a To Do line at the value column starts a numbered item, %d)" % expected, at)
            elif column != text_column:
                fail("a To Do continuation aligns under its item's text, at column %d, not %d" % (text_column + 1, column + 1),
                     at)
    elif label in ("Dependencies", "Reviewers"):
        for at, column, content in field["more"]:
            if column != field["column"]:
                fail("a '%s:' continuation aligns under the value, at column %d, not %d" % (label, field["column"] + 1, column + 1),
                     at)
        if label == "Dependencies":
            items = [item.strip() for item in " ".join([value] + [content for _, _, content in field["more"]]).split(",")]
            if any(not item for item in items) or ("None" in items and len(items) > 1):
                fail("'Dependencies:' is None or a comma-separated list, with nothing empty between its commas")
    elif label == "ISA":
        tokens = value.split(" | ")
        if any(token not in ISA_TOKENS for token in tokens):
            fail("'ISA:' tokens come from {%s}, separated by ' | '" % ", ".join(ISA_TOKENS))
        elif len(set(tokens)) != len(tokens):
            fail("'ISA:' names a token twice")
    elif label == "Thread-safety" and value not in THREAD_SAFETY:
        fail("'Thread-safety:' is one of %s" % ", ".join(THREAD_SAFETY))
    elif label == "License" and not PROLOG_LICENSE.match(line):
        fail("'License:' is an SPDX id, exactly two spaces, then 'Copyright: <holder>'")
    return problems


# ---------------------------------------------------------------------------------------------------
# r8: three-space indentation in C and C++


def blank_literals(lines):
    """Returns (code, directives): each line's code with comments removed, string and character literals
    reduced to empty quotes and preprocessor lines emptied, carrying block comments and raw strings
    across lines; and, per line, the name of the preprocessor directive it begins ('' for a directive's
    continuation line, None for a line that is not one). What is left is enough to see braces and
    parentheses, which is all the indent check needs."""
    code = []
    directives = []
    in_comment = False
    raw_end = None
    continued = False
    for line in lines:
        directive = None
        if not in_comment and raw_end is None:
            if continued:
                directive = ""
            else:
                match = re.match(r"\s*#\s*(\w*)", line)
                if match:
                    directive = match.group(1)
        out = []
        i = 0
        while i < len(line):
            if in_comment:
                end = line.find("*/", i)
                if end < 0:
                    break
                in_comment = False
                out.append(" ")
                i = end + 2
                continue
            if raw_end is not None:
                end = line.find(raw_end, i)
                if end < 0:
                    break
                i = end + len(raw_end)
                raw_end = None
                out.append('""')
                continue
            c = line[i]
            if line.startswith("//", i):
                break
            if line.startswith("/*", i):
                in_comment = True
                i += 2
                continue
            if c == '"':
                if re.search(r"(?:^|[^A-Za-z0-9_])(?:u8|u|U|L)?R$", line[:i]):
                    opening = line.find("(", i)
                    if opening >= 0:
                        raw_end = ")" + line[i + 1:opening] + '"'
                        i = opening + 1
                        continue
                i += 1
                while i < len(line) and line[i] != '"':
                    i += 2 if line[i] == "\\" else 1
                out.append('""')
                i += 1
                continue
            if c == "'":
                # A digit separator, 1'000 or 0xFF'FF, sits inside a number; L'0' and u8'a' are prefixed
                # character literals, whose token starts with a letter rather than a digit.
                token = re.search(r"[A-Za-z0-9_.']*$", line[:i]).group(0)
                if token[:1].isdigit() and i + 1 < len(line) and line[i + 1].isalnum():
                    i += 1
                    continue
                i += 1
                while i < len(line) and line[i] != "'":
                    i += 2 if line[i] == "\\" else 1
                out.append("''")
                i += 1
                continue
            out.append(c)
            i += 1
        if directive is not None:
            continued = line.endswith("\\")
            code.append("")
        else:
            code.append("".join(out))
        directives.append(directive)
    return code, directives


def brace_kind(before, previous_end, inside_initializer):
    """'init' for a braced initializer, whose rows clang-format aligns rather than indents; 'block'
    for anything whose body is indented one step: a function, a control statement, a struct, an enum, a
    lambda or a bare scope. clang-format writes a space before a block's brace and none before a braced
    list, so `S s{` and `TABLE[]{` are lists where `struct S {` and `) {` are blocks."""
    if inside_initializer:
        return "init"
    text = before.rstrip()
    if not text:
        return "init" if previous_end in ("=", "(", ",", "[", "?") else "block"
    if text[-1] in "=(,[{?" or re.search(r"(^|[^A-Za-z0-9_])return$", text):
        return "init"
    if before[-1:] and (before[-1].isalnum() or before[-1] in "_>]"):
        return "init"
    return "block"


LABEL = re.compile(r"[A-Za-z_]\w*\s*:(?!:)")
CASE_LABEL = re.compile(r"(case\b.*|default\s*):")
ACCESS = re.compile(r"(public|private|protected)\s*:")
CONTROL_HEAD = re.compile(r"(\}\s*)?(else\s+)?(if|for|while)\s*\(")
BARE_HEAD = re.compile(r"(\}\s*)?(else|do)")
CARRIED_HEAD = re.compile(r"template\s*<.*>|\[\[.*\]\]")


def check_indent(lines):
    """r8, made mechanical over the brace structure rather than over every line, because a continuation
    line is aligned rather than indented and belongs to no step. A statement that starts inside a block
    starts exactly three spaces past the line that opened it, a brace-less body of if, for, while, else
    or do three past its head, a closing brace lines up with its opener, and a statement at file scope
    starts in column one. The exceptions are the ones .clang-format itself makes: a case label and a goto
    label sit at the opener's column (IndentCaseLabels false and IndentGotoLabels true, LLVM's), an access
    specifier one column in (AccessModifierOffset -2 on a three-space step), and an extern "C" block's
    body is not indented at all. Each branch of an #if is read from the state the #if found, and the
    first branch's state is kept at #endif, so alternative opening lines do not unbalance the braces."""
    problems = []
    code, directives = blank_literals(lines)
    state = {"stack": [], "depth": 0, "previous": "", "statement": 0, "text": "", "body": None, "carry": None}
    conditionals = []
    for index, raw in enumerate(lines):
        directive = directives[index]
        if directive is not None:
            if directive in ("if", "ifdef", "ifndef"):
                conditionals.append({"start": copy.deepcopy(state), "first": None})
            elif directive in ("elif", "else", "elifdef", "elifndef") and conditionals:
                frame = conditionals[-1]
                if frame["first"] is None:
                    frame["first"] = copy.deepcopy(state)
                state = copy.deepcopy(frame["start"])
            elif directive == "endif" and conditionals:
                frame = conditionals.pop()
                if frame["first"] is not None:
                    state = frame["first"]
            continue
        line_code = code[index]
        text = line_code.strip()
        if not text:
            continue
        indent = len(raw) - len(raw.lstrip(" "))
        stack = state["stack"]
        top = stack[-1] if stack else None
        body = state["body"]
        state["body"] = None
        carry = state["carry"]
        state["carry"] = None
        in_enum = top is not None and top["enum"]
        starts = body is not None or carry is not None or (state["depth"] == 0 and (
            state["previous"] in ("", ";", "{", "}", ":") or (state["previous"] == "," and in_enum)))
        if starts and not text.startswith("}") and not (text.startswith("{") and body is not None):
            if body is not None:
                expected = body + CPP_STEP
            elif carry is not None:
                expected = carry
            elif top is None:
                expected = 0
            elif top["kind"] == "init":
                expected = None
            elif top["extern"]:
                expected = top["indent"]
            elif CASE_LABEL.match(text) and top["switch"]:
                expected = top["indent"]
            elif ACCESS.match(text):
                expected = top["indent"] + CPP_STEP - 2
            elif LABEL.match(text) and not CASE_LABEL.match(text):
                expected = top["indent"]
            else:
                expected = top["indent"] + CPP_STEP
            if expected is not None and indent != expected:
                problems.append((index + 1, "r8", "this statement starts at column %d; its block puts it at column %d"
                                 % (indent + 1, expected + 1)))
            state["statement"] = indent
            state["text"] = text
            if CARRIED_HEAD.fullmatch(text) and expected is not None:
                state["carry"] = expected
        first = len(line_code) - len(line_code.lstrip(" "))
        for position, c in enumerate(line_code):
            if c in "([":
                state["depth"] += 1
            elif c in ")]":
                state["depth"] = max(0, state["depth"] - 1)
            elif c == "{":
                before = line_code[:position]
                kind = brace_kind(before, state["previous"], bool(stack) and stack[-1]["kind"] == "init")
                owner = state["text"]
                entry = {"kind": kind, "indent": state["statement"], "saved": None,
                         "switch": kind == "block" and bool(re.match(r"(\}\s*)?switch\s*\(", owner)),
                         "extern": kind == "block" and bool(re.fullmatch(r'extern\s*""', before.strip())),
                         "enum": kind == "block" and bool(re.match(r"(typedef\s+)?enum\b", owner)) and "(" not in before}
                if kind == "block" and state["depth"] > 0:
                    # A lambda's body: indented from the line its brace opens on, and outside the parentheses
                    # the call around it left open.
                    entry["indent"] = indent
                    entry["saved"] = state["depth"]
                    state["depth"] = 0
                stack.append(entry)
            elif c == "}":
                if not stack:
                    problems.append((index + 1, "r8", "a closing brace with no opening brace before it"))
                    continue
                entry = stack.pop()
                if entry["saved"] is not None:
                    state["depth"] = entry["saved"]
                if position == first:
                    if entry["kind"] == "block" and indent != entry["indent"]:
                        problems.append((index + 1, "r8", "this closing brace is at column %d; the line that opened it starts "
                                         "at column %d" % (indent + 1, entry["indent"] + 1)))
                    state["statement"] = entry["indent"]
                    state["text"] = text
        state["previous"] = text[-1]
        if state["depth"] == 0 and text[-1] == ")" and CONTROL_HEAD.match(state["text"]):
            state["body"] = state["statement"]
        elif BARE_HEAD.fullmatch(text):
            state["body"] = state["statement"]
    return problems


# ---------------------------------------------------------------------------------------------------
# Python: the tagged deviations, and the four-space step they allow


def check_python(data):
    """en3: r17's prolog cannot be written in Python, so the file says so on its first line, with a
    reason, instead of deviating silently. r8's exemption is .editorconfig's four spaces, so every
    indent steps by four. A file whose bytes already broke tc2 or the ASCII rule is not tokenized, because
    that is where Python releases disagree; one that does not compile is reported under 'syntax', since
    its indentation cannot be measured."""
    problems = []
    text = data.decode("latin-1")
    if not PYTHON_TAG.match(text):
        problems.append((1, "en3", "a Python file opens with '# RULE-DEV:r17 <why>', standing in for the r17 prolog"))
    if re.search(rb"[^\t\n\r\x20-\x7e]|\r(?!\n)|(?<!\r)\n", data):
        return problems
    source = text.replace("\r\n", "\n")
    try:
        compile(source, "<file>", "exec")
    except (SyntaxError, ValueError) as error:
        problems.append((getattr(error, "lineno", None) or 0, "syntax", "not valid Python, so its indentation cannot be "
                         "measured: %s" % getattr(error, "msg", error)))
        return problems
    widths = [0]
    try:
        for token in tokenize.generate_tokens(io.StringIO(source).readline):
            if token.type == tokenize.INDENT:
                width = len(token.string)
                if width - widths[-1] != PYTHON_STEP:
                    problems.append((token.start[0], "r8", "this block is indented %d past its parent; Python steps by %d "
                                     "(.editorconfig RULE-DEV:r8)" % (width - widths[-1], PYTHON_STEP)))
                widths.append(width)
            elif token.type == tokenize.DEDENT and len(widths) > 1:
                widths.pop()
    except Exception as error:
        # Defensive: source that compiles tokenizes, so no input reaches this, and the self-test cannot.
        problems.append((0, "syntax", "cannot tokenize this file: %s" % error))
    return problems


# ---------------------------------------------------------------------------------------------------
# One file, and a list of them


def check_file(rel, kind, data):
    """Every rule the file's class carries, as (line, rule, message) tuples sorted by line."""
    problems = check_bytes(data, kind)
    lines = split_lines(data)
    if kind == CPP:
        prolog, inner = check_prolog(lines, rel.split("/")[-1])
        problems.extend(prolog)
        problems.extend(check_width(lines, kind, inner))
        problems.extend(check_indent(lines))
    elif kind == PYTHON:
        problems.extend(check_width(lines, kind))
        problems.extend(check_python(data))
    else:
        problems.extend(check_width(lines, kind))
    return sorted(problems, key=lambda p: (p[0], p[1]))


def check_files(files, root=REPO):
    """Reads and judges each (rel, kind) pair; a file that cannot be read is a problem, not a crash."""
    problems = []
    for rel, kind in files:
        try:
            with open(os.path.join(root, *rel.split("/")), "rb") as handle:
                data = handle.read()
        except OSError as error:
            problems.append((rel, 0, "scope", "cannot be read: %s" % error.strerror))
            continue
        problems.extend((rel, line, rule, message) for line, rule, message in check_file(rel, kind, data))
    return problems


# ---------------------------------------------------------------------------------------------------
# clang-format, pinned


def format_check(files, exe, root=REPO):
    """Runs clang-format in dry-run over the C++ files judged. The verdict is pinned to one release,
    because two releases can format one file two ways and CI must not change its mind when a runner
    image does; 18.1.3 is what every session since M1 verified the tree against."""
    if os.sep in exe or "/" in exe:
        found = os.path.abspath(exe) if os.path.isfile(exe) else None
    else:
        found = shutil.which(exe)
    if found is None:
        return [("clang-format", 0, FORMAT_RULE, "%s was not found; pip install clang-format==%s, or pass --clang-format <path>"
                 % (exe, CLANG_FORMAT_VERSION))]
    try:
        version = subprocess.run([found, "--version"], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, cwd=root)
    except OSError as error:
        return [("clang-format", 0, FORMAT_RULE, "%s cannot be run: %s" % (found, error.strerror))]
    match = re.search(r"clang-format version (\d+\.\d+\.\d+)", version.stdout.decode("utf-8", "replace"))
    if not match or match.group(1) != CLANG_FORMAT_VERSION:
        return [("clang-format", 0, FORMAT_RULE, "the formatter verdict is pinned to clang-format %s, and %s is %s"
                 % (CLANG_FORMAT_VERSION, found, match.group(1) if match else "an unknown version"))]
    cpp = [rel for rel, kind in files if kind == CPP]
    problems = []
    for start in range(0, len(cpp), 40):
        batch = cpp[start:start + 40]
        done = subprocess.run([found, "--dry-run", "--Werror", "--style=file"] + batch, stdout=subprocess.PIPE,
                              stderr=subprocess.STDOUT, cwd=root)
        if done.returncode != 0:
            output = done.stdout.decode("utf-8", "replace")
            reported = set()
            for hit in re.finditer(r"^(.+?):(\d+):\d+: (?:error|warning): (.*)$", output, re.M):
                where = os.path.relpath(os.path.join(root, hit.group(1)), root).replace(os.sep, "/")
                if (where, hit.group(2)) not in reported:
                    reported.add((where, hit.group(2)))
                    problems.append((where, int(hit.group(2)), FORMAT_RULE, "clang-format would change this line"))
            if not reported:
                problems.append((" ".join(batch), 0, FORMAT_RULE, "clang-format failed: %s" % output.strip()[:300]))
    return problems


# ---------------------------------------------------------------------------------------------------
# Reporting and the command line


def ascii_only(text):
    """Every message is ASCII, so a report reaches any console whole: a file's own bytes quoted in a
    message come out as escapes, whatever the output's encoding."""
    return text.encode("ascii", "backslashreplace").decode("ascii")


def annotate(rel, line, rule, message):
    """A GitHub Actions error annotation, so a failure lands on the line in the pull request's diff."""
    def escape(text, extra=""):
        text = text.replace("%", "%25").replace("\r", "%0D").replace("\n", "%0A")
        for c in extra:
            text = text.replace(c, "%%%02X" % ord(c))
        return text
    where = "file=%s" % escape(rel, ":,")
    if line:
        where += ",line=%d" % line
    return "::error %s,title=%s::%s" % (where, escape("GCS " + rule, ":,"), escape(message))


def show(problems):
    on_github = os.environ.get("GITHUB_ACTIONS") == "true"
    for rel, line, rule, message in problems:
        rel = ascii_only(rel)
        message = ascii_only(message)
        print("%s:%s %s: %s" % (rel, "%d:" % line if line else "", rule, message))
        if on_github:
            print(annotate(rel, line, rule, message))


def parse(argv):
    """The command line as a dict, or UsageError."""
    options = {"self_test": False, "format": False, "exe": None, "paths": []}
    index = 0
    while index < len(argv):
        arg = argv[index]
        if arg == "--self-test":
            options["self_test"] = True
        elif arg == "--format":
            options["format"] = True
        elif arg == "--clang-format" or arg.startswith("--clang-format="):
            if "=" in arg:
                value = arg.split("=", 1)[1]
            elif index + 1 < len(argv) and not argv[index + 1].startswith("-"):
                index += 1
                value = argv[index]
            else:
                value = ""
            if not value:
                raise UsageError("--clang-format needs a path")
            options["exe"] = value
        elif arg.startswith("-"):
            raise UsageError("unknown option %s" % arg)
        else:
            options["paths"].append(arg)
        index += 1
    if options["self_test"] and (options["format"] or options["exe"] or options["paths"]):
        raise UsageError("--self-test takes no other argument")
    if options["exe"] and not options["format"]:
        raise UsageError("--clang-format names the formatter --format runs, so it needs --format")
    return options


def main(argv):
    try:
        options = parse(argv)
        if options["self_test"]:
            return self_test()
        chosen = select(options["paths"])
    except UsageError as error:
        print("validate_gcs: %s" % ascii_only(str(error)))
        print(USAGE)
        return 2
    for note in chosen.notes:
        print(ascii_only(note))
    if options["paths"] and not chosen.files and not chosen.problems:
        print("validate_gcs: nothing to check")
        return 2
    problems = chosen.problems + check_files(chosen.files)
    if options["format"]:
        problems.extend(format_check(chosen.files, options["exe"] or "clang-format"))
    show(problems)
    touched = len({p[0] for p in problems})
    print("validate_gcs: %d file%s judged, %d problem%s in %d place%s" % (
        len(chosen.files), "" if len(chosen.files) == 1 else "s", len(problems), "" if len(problems) == 1 else "s",
        touched, "" if touched == 1 else "s"))
    return 1 if problems else 0


# ---------------------------------------------------------------------------------------------------
# The self-test: every rule, shown firing


GOOD_PROLOG = [
    "/*",
    " * File: Good.cpp",
    " * Version: v0.1.0",
    " * Owner: David William Bull",
    " * Created: 2026-09-25",
    " * Last Modified: 2026-09-25",
    " * Description: A file every rule accepts, which each case below breaks in one place.",
    " * To Do: 1) Stay clean.",
    " *        2) Keep a continuation aligned under the",
    " *           item it continues.",
    " * Dependencies: typedefs.h, memory management.h,",
    " *               stdio.h",
    " * ISA: Scalar | AVX2",
    " * Thread-safety: Reentrant",
    " * Reviewers: David William Bull",
    " * License: MIT  Copyright: David William Bull",
    " */",
]
GOOD_BODY = [
    "#include \"typedefs.h\"",
    "#define PAIR(a, b) { a, \\",
    "                     b }",
    "",
    "static const ui32 TABLE[] = {",
    "    1, 2,   // a row clang-format aligns rather than indents",
    "};",
    "",
    "enum COLOUR : ui8 {",
    "   COLOUR_RED,",
    "   COLOUR_BLUE,",
    "};",
    "",
    "si32 Good(csi32 a,",
    "          csi32 b) {",
    "   if(a) {",
    "      switch(b) {",
    "      case 1: return 1;",
    "      default: break;",
    "      }",
    "   } else {",
    "      Call(\"a { brace in a string\", '{');   // and { one in a comment",
    "      Call(L'0', L'{', R\"x(\")\" { \")x\", u8R\"(})\");   // each literal hides a brace from a wrong lexer",
    "      Call(1'000, '}', \"\\\" {\", '\\'', '{');",
    "   }",
    "   for(ui32 i = 0; i < a;",
    "       ++i)",
    "      Call(i);",
    "   /* a block comment { with a brace",
    "      that runs over two lines */",
    "   return b;",
    "}",
]
# Layouts the indent check must accept, each appended to the clean file on its own: how clang-format lays
# the construct out once it is too long to join onto one line, shortened here, so the formatter itself would
# join most of them. They are the constructs the check has an exception for, or once reported falsely.
ACCEPTED_SHAPES = [
    ("an extern \"C\" block", ["extern \"C\" {", "si32 Exported(si32 a);", "}"]),
    ("an extern \"C\" function", ["extern \"C\" si32 Exported(si32 x) {", "   return x;", "}"]),
    ("a class with an access specifier", ["class X {", " public:", "   si32 a;", "};"]),
    ("a nested initializer", ["static const P T[] = {", "    P{", "        1,", "    },", "};"]),
    ("a nested initializer's brace on its own line", ["static const P T[] = {", "    {", "        1,", "    },", "};"]),
    ("a returned initializer", ["P F(si32 a) {", "   return {", "       a,", "   };", "}"]),
    ("a braced list after a name", ["void F() {", "   S s{", "       1,", "   };", "   G();", "}"]),
    ("a lambda argument", ["void F() {", "   Sort(a, b, [](si32 x, si32 y) {", "      if(x) {", "         return x < y;",
                           "      }", "      return false;", "   });", "   G();", "}"]),
    ("a goto label", ["void F() {", "   if(x) goto done;", "   G();", "done:", "   H();", "}"]),
    ("a comment opened on a directive", ["#endif /* the floor, which BuildGuards.h enforces for",
                                         "          every unit */", "void F() {", "   G();", "}"]),
    ("a function returning an enum, wrapped", ["static enum COLOUR Pick(ui32 x) {", "   ui32 first  = 1,",
                                               "        second = 2;", "   return COLOUR_RED;", "}"]),
    ("two opening lines under #if", ["void F() {", "#if defined(A)", "   if(a) {", "#else", "   if(b) {", "#endif",
                                      "      X();", "   }", "}", "void H();"]),
    ("a bare scope first in its block", ["void F() {", "   {", "      ui32 x = 1;", "   }", "}"]),
    ("a do loop and an else without braces", ["void F() {", "   do {", "      G();", "   } while(x);", "   if(x)",
                                              "      G();", "   else", "      H();", "}"]),
    ("a template head", ["template <typename T>", "T Max(T a, T b) {", "   return a;", "}"]),
    ("a formatter-aligned macro", ["#define LONG(a, b)" + " " * 161 + "\\", "   ((a) + (b))"]),
]


def cpp(lines):
    return ("\r\n".join(lines) + "\r\n").encode("latin-1")


def replaced(lines, old, new):
    out = list(lines)
    out[out.index(old)] = new
    return out


def inserted(lines, after, new):
    out = list(lines)
    out.insert(out.index(after) + 1, new)
    return out


def matches(got, wanted):
    """True when every wanted (rule, fragment) pair names a distinct problem and nothing else was found."""
    left = list(got)
    for rule, fragment in wanted:
        hit = next((p for p in left if p[1] == rule and fragment in p[2]), None)
        if hit is None:
            return False
        left.remove(hit)
    return not left


def file_cases():
    """(name, rel, bytes, wanted): each case breaks one check and names the problem it must produce."""
    good = GOOD_PROLOG + GOOD_BODY
    ret = "   return b;"
    lead = "   return b; // "
    mark = WIDTH_MARK[CPP]
    xml_lead = "  <Import Project=\""
    xml_tail = "\" />"
    py_good = ["# RULE-DEV:r17 the reason", "def f():", "    return 1", "", "", "def g():", "    if f():", "        return 2"]
    prolog = [
        ("one space before Copyright:", " * License: MIT  Copyright: David William Bull", " * License: MIT Copyright: David William Bull",
         "exactly two spaces"),
        ("the ISA token typedefs.h gets wrong", " * ISA: Scalar | AVX2", " * ISA: Scalar | AVX512", "tokens come from"),
        ("an ISA separator without spaces", " * ISA: Scalar | AVX2", " * ISA: Scalar|AVX2", "tokens come from"),
        ("an ISA token named twice", " * ISA: Scalar | AVX2", " * ISA: AVX2 | AVX2", "names a token twice"),
        ("a Thread-safety outside the three tokens", " * Thread-safety: Reentrant", " * Thread-safety: Thread-compatible",
         "'Thread-safety:' is one of"),
        ("a File: naming another file", " * File: Good.cpp", " * File: Other.cpp", "says Other.cpp"),
        ("a date that is not a date", " * Created: 2026-09-25", " * Created: 2026-02-30", "not a calendar date"),
        ("a date without its dashes", " * Created: 2026-09-25", " * Created: 20260925", "YYYY-MM-DD"),
        ("modified before it was created", " * Created: 2026-09-25", " * Created: 2026-09-26", "earlier than"),
        ("a version without its v", " * Version: v0.1.0", " * Version: 0.1.0", "vMAJOR.MINOR"),
        ("two spaces after a label", " * Owner: David William Bull", " * Owner:  David William Bull", "takes one space"),
        ("no space after a label, and only that reported", " * File: Good.cpp", " * File:Good.cpp", "takes one space"),
        ("None beside a dependency", " * Dependencies: typedefs.h, memory management.h,", " * Dependencies: None, memory management.h,",
         "comma-separated"),
        ("a To Do opening at 2)", " * To Do: 1) Stay clean.", " * To Do: 2) Stay clean.", "opens with item 1)"),
        ("a To Do item misnumbered", " *        2) Keep a continuation aligned under the",
         " *        3) Keep a continuation aligned under the", "should be 2)"),
        ("an unnumbered line at the To Do value column", " *        2) Keep a continuation aligned under the",
         " *        Keep a continuation aligned under the", "starts a numbered item"),
        ("a To Do continuation misaligned", " *           item it continues.", " *          item it continues.",
         "aligns under its item"),
        ("a Dependencies continuation misaligned", " *               stdio.h", " *              stdio.h", "aligns under the value"),
        ("an empty Dependencies item", " * Dependencies: typedefs.h, memory management.h,", " * Dependencies: typedefs.h,, memory management.h,",
         "comma-separated"),
        ("a continuation of a one-line field", " * Description: A file every rule accepts, which each case below breaks in one place.",
         " * Description: A file every rule accepts, which each case below breaks in one place.\r\n *              and more",
         "takes one line"),
        ("a blank prolog line with a trailing space", " * Thread-safety: Reentrant", " * Thread-safety: Reentrant\r\n * ",
         "exactly ' *'"),
        ("an unknown field", " * Reviewers: David William Bull", " * Reviewers: David William Bull\r\n * Author: X", "twelve fields"),
        ("a prolog line over 150 columns", " * Owner: David William Bull", " * Owner: David William Bull" + " x" * 62, "wrap at 150"),
    ]
    cases = [
        ("a clean C++ file", "src/Good.cpp", cpp(good), []),
        ("a tab after code", "src/Good.cpp", cpp(replaced(good, ret, ret + "\t// x")), [("r8", "three spaces")]),
        ("a byte that is not ASCII", "src/Good.cpp", cpp(replaced(good, ret, ret + " // caf\xe9")), [("ascii", "0xE9")]),
        ("a control byte", "src/Good.cpp", cpp(replaced(good, ret, ret + "\x0c")), [("ascii", "0x0C")]),
        ("a DEL byte", "src/Good.cpp", cpp(replaced(good, ret, ret + " // \x7f")), [("ascii", "0x7F")]),
        ("a UTF-8 BOM on C++", "src/Good.cpp", UTF8_BOM + cpp(good), [("ascii", "0xEF"), ("r17", "must open")]),
        ("an LF line ending", "src/Good.cpp", cpp(good).replace(b"return b;\r\n", b"return b;\n"), [("tc2", "LF rather")]),
        ("a CR on its own", "src/Good.cpp", cpp(replaced(good, ret, ret + "\r// x")), [("tc2", "not followed")]),
        ("no CRLF after the last line", "src/Good.cpp", cpp(good)[:-2], [("tc2", "no CRLF after")]),
        ("150 columns", "src/Good.cpp", cpp(replaced(good, ret, lead + "x" * (SOFT_WIDTH - len(lead)))), []),
        ("151 columns", "src/Good.cpp", cpp(replaced(good, ret, lead + "x" * (SOFT_WIDTH + 1 - len(lead)))), [("e2", "wrap at")]),
        ("180 columns marked WIDTH-EXEMPT", "src/Good.cpp",
         cpp(replaced(good, ret, lead + "x" * (HARD_WIDTH - len(lead) - len(mark)) + mark)), []),
        ("181 columns, even marked", "src/Good.cpp",
         cpp(replaced(good, ret, lead + "x" * (HARD_WIDTH + 1 - len(lead) - len(mark)) + mark)), [("e2", "hard cap")]),
        ("a padded /* line", "src/Good.cpp", cpp(replaced(good, "/*", "/*" + " " * 200)), [("e2", "hard cap")]),
        ("a padded */ line", "src/Good.cpp", cpp(replaced(good, " */", " */" + " " * 200)), [("e2", "hard cap")]),
        ("no prolog", "src/Good.cpp", cpp(GOOD_BODY), [("r17", "must open")]),
        ("no closing line", "src/Good.cpp", cpp(GOOD_PROLOG[:-1] + ["si32 x;"]), [("r17", "closing")]),
        ("a History: field", "src/Good.cpp", cpp(inserted(good, " * Reviewers: David William Bull", " * History: made")),
         [("r17", "History")]),
        ("a missing field", "src/Good.cpp", cpp([line for line in good if not line.startswith(" * Owner:")]), [("r17", "'Owner:' field is missing")]),
        ("a field twice", "src/Good.cpp", cpp(inserted(good, " * Owner: David William Bull", " * Owner: X")), [("r17", "appears 2 times")]),
        ("two fields out of order", "src/Good.cpp",
         cpp(replaced(replaced(good, " * Version: v0.1.0", " * Owner: X"), " * Owner: David William Bull", " * Version: v0.1.0")),
         [("r17", "comes after")]),
        ("a prolog line without its space", "src/Good.cpp",
         cpp(inserted(good, " * Reviewers: David William Bull", " *junk")), [("r17", "starts with exactly")]),
        ("a To Do reaching 10), continued", "src/Good.cpp",
         cpp(replaced(good, " *           item it continues.", " *           item it continues.\r\n" + "\r\n".join(
             " *        %d) Item." % n for n in range(3, 11)) + "\r\n *            its tenth continuation.")), []),
        ("a four-space block", "src/Good.cpp", cpp(replaced(good, ret, "    return b;")), [("r8", "statement starts")]),
        ("a two-space block", "src/Good.cpp", cpp(replaced(good, "      Call(\"a { brace in a string\", '{');   // and { one in a comment",
                                                            "     Call(\"a { brace in a string\", '{');   // and { one in a comment")),
         [("r8", "statement starts")]),
        ("a brace-less body out of step", "src/Good.cpp", cpp(replaced(good, "      Call(i);", "     Call(i);")), [("r8", "statement starts")]),
        ("a closing brace out of line", "src/Good.cpp", cpp(replaced(good, "   } else {", "    } else {")), [("r8", "closing brace is at")]),
        ("a stray closing brace", "src/Good.cpp", cpp(good + ["}"]), [("r8", "no opening brace")]),
        ("an indented statement at file scope", "src/Good.cpp", cpp(good + ["   si32 Other(void);"]), [("r8", "statement starts")]),
        ("an enum member out of step", "src/Good.cpp", cpp(replaced(good, "   COLOUR_BLUE,", "    COLOUR_BLUE,")), [("r8", "statement starts")]),
        ("an extern \"C\" block indented", "src/Good.cpp", cpp(good + ["extern \"C\" {", "   si32 Exported(si32 a);", "}"]),
         [("r8", "statement starts")]),
        ("a label out of step", "src/Good.cpp", cpp(good + ["void F() {", "   done:", "   H();", "}"]), [("r8", "statement starts")]),
        ("a class body unindented", "src/Good.cpp", cpp(good + ["class X {", " public:", "si32 a;", "};"]), [("r8", "statement starts")]),
        ("a bare scope's body out of step", "src/Good.cpp", cpp(good + ["void F() {", "   {", "    G();", "   }", "}"]),
         [("r8", "statement starts")]),
        ("an else body out of step", "src/Good.cpp", cpp(good + ["void F() {", "   if(x)", "      G();", "   else", "     H();", "}"]),
         [("r8", "statement starts")]),
        ("a line after a template head, indented", "src/Good.cpp", cpp(good + ["template <typename T>", "  T Max(T a, T b);"]),
         [("r8", "statement starts")]),
        ("a Python file with its tag", "tests/good.py", cpp(py_good), []),
        ("a Python file without its tag", "tests/good.py", cpp(py_good[1:]), [("en3", "RULE-DEV")]),
        ("a Python tag with no reason", "tests/good.py", cpp(["# RULE-DEV:r17 "] + py_good[1:]), [("en3", "RULE-DEV")]),
        ("a Python block indented three", "tests/good.py", cpp(replaced(py_good, "    return 1", "   return 1")), [("r8", "steps by 4")]),
        ("a Python tab", "tests/good.py", cpp(replaced(py_good, "    return 1", "    return 1\t# x")), [("r8", "four spaces")]),
        ("Python that does not compile", "tests/good.py", cpp(replaced(py_good, "def f():", "def f(:")), [("syntax", "not valid")]),
        ("Python with a CR on its own", "tests/good.py", cpp(replaced(py_good, "    return 1", "    return 1\r\x94")),
         [("tc2", "not followed"), ("ascii", "0x94")]),
        ("Python at 151 columns", "tests/good.py", cpp(replaced(py_good, "    return 1", "    return 1  # " + "x" * 135)),
         [("e2", "wrap at")]),
        ("Python at 159 columns, marked", "tests/good.py",
         cpp(replaced(py_good, "    return 1", "    return 1  # " + "x" * 127 + " # WIDTH-EXEMPT")), []),
        ("project XML at 180 columns after a BOM", "tests/X.vcxproj",
         UTF8_BOM + cpp([xml_lead + "x" * (HARD_WIDTH - len(xml_lead) - len(xml_tail)) + xml_tail, "</Project>"]), []),
        ("project XML at 181 columns", "tests/X.vcxproj",
         cpp(["<Project>", xml_lead + "x" * (HARD_WIDTH + 1 - len(xml_lead) - len(xml_tail)) + xml_tail, "</Project>"]),
         [("e2", "hard cap")]),
        ("a project-XML tab", "tests/X.vcxproj", cpp(["<Project>", "\t<X />", "</Project>"]), [("r8", "indent with spaces")]),
    ]
    for name, old, new, fragment in prolog:
        cases.append((name, "src/Good.cpp", cpp(replaced(good, old, new)), [("r17", fragment)]))
    for name, shape in ACCEPTED_SHAPES:
        cases.append(("accepts " + name, "src/Good.cpp", cpp(good + shape), []))
    return cases


def path_cases():
    """(rel, kind): what verdict_for must say, on every host."""
    return [
        ("include/typedefs.h", "exempt"), ("Include/typedefs.h", "unknown"), ("src/Ir.h", "judge"),
        ("tests/unit/Check.h", "judge"), ("tests/fixtures/minimal/src/word/document.xml", "skip"),
        ("tests/build/minimal.docx", "skip"), ("tests/Build/Probe.cpp", "unknown"), ("tests/x64/Release/DOCXtoMD.Tests.exe", "skip"),
        ("tests/__pycache__/make_fixtures.cpython-311.pyc", "skip"), ("tests/__PyCache__/x.py", "unknown"),
        ("tests/DOCXtoMD.Tests.vcxproj.user", "skip"), ("tests/notes.txt", "unknown"), ("docs/CONVERSION_REFERENCE.md", "outside"),
        ("DOCXtoMD.vcxproj", "outside"), ("src/Upper.CPP", "judge"), ("SRC/Ir.h", "unknown"),
    ]


def parse_cases():
    """(argv, wanted): the options parse() must return, or None where it must refuse the command line."""
    return [
        ([], {"self_test": False, "format": False, "exe": None, "paths": []}),
        (["--format", "src"], {"self_test": False, "format": True, "exe": None, "paths": ["src"]}),
        (["--format", "--clang-format", "cf"], {"self_test": False, "format": True, "exe": "cf", "paths": []}),
        (["--clang-format=cf", "--format"], {"self_test": False, "format": True, "exe": "cf", "paths": []}),
        (["--self-test"], {"self_test": True, "format": False, "exe": None, "paths": []}),
        (["--bogus"], None), (["--self-test", "src"], None), (["--self-test", "--format"], None),
        (["--clang-format", "cf"], None), (["--clang-format", "--format"], None), (["--format", "--clang-format"], None),
        (["--format", "--clang-format="], None),
    ]


def tree_cases(root):
    """Builds small repositories under root and returns (name, ok, got) for select() and check_files()."""
    def make(base, files):
        for rel, data in files.items():
            path = os.path.join(base, *rel.split("/"))
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "wb") as handle:
                handle.write(data)
        return base

    good = cpp(GOOD_PROLOG + GOOD_BODY)
    py = cpp(["# RULE-DEV:r17 the reason", "x = 1"])
    full = make(os.path.join(root, "full"), {"src/Good.cpp": good, "tests/ok.py": py, "tests/notes.txt": b"",
                                             "include/typedefs.h": b"junk", "docs/x.md": b""})
    empty = make(os.path.join(root, "empty"), {"tests/ok.py": py})
    os.makedirs(os.path.join(empty, "src"))
    variant = make(os.path.join(root, "variant"), {"src/Good.cpp": good, "tests/ok.py": py, "Include/typedefs.h": b"junk",
                                                   "tests/Build/probe.cpp": good})
    missing = make(os.path.join(root, "missing"), {"tests/ok.py": py})
    results = []

    def run(name, args, base, wanted_files, wanted_problems, wanted_notes=0):
        try:
            chosen = select(args, base)
            got = ([rel for rel, _ in chosen.files], [(p[0], p[3]) for p in chosen.problems], len(chosen.notes))
            ok = (got[0] == wanted_files and len(got[1]) == len(wanted_problems)
                  and all(any(rel == w[0] and w[1] in text for rel, text in got[1]) for w in wanted_problems) and got[2] == wanted_notes)
        except UsageError as error:
            got, ok = "usage error: %s" % error, wanted_files is None
        results.append((name, ok, got))

    run("a default run judges src/ and tests/, and fails what has no class", [], full,
        ["src/Good.cpp", "tests/ok.py"], [("tests/notes.txt", "no rules")])
    run("a default run over an empty src/ is a problem", [], empty, ["tests/ok.py"], [("src", "nothing here")])
    run("naming the root is the default run", [full], full, ["src/Good.cpp", "tests/ok.py"], [("tests/notes.txt", "no rules")], 2)
    run("naming the root keeps the empty-scope problem", [empty], empty, ["tests/ok.py"], [("src", "nothing here")], 2)
    run("naming include/ judges nothing", [os.path.join(full, "include", "typedefs.h")], full, [], [], 1)
    run("naming docs/ judges nothing", [os.path.join(full, "docs")], full, [], [], 1)
    run("naming one file twice reports it once", [os.path.join(full, "tests", "notes.txt")] * 2, full, [], [("tests/notes.txt", "no rules")])
    run("naming tests/ twice judges it once", [os.path.join(full, "tests")] * 2, full, ["tests/ok.py"], [("tests/notes.txt", "no rules")])
    run("directories differing from include/ and tests/build/ only in case", [], variant, ["src/Good.cpp", "tests/ok.py"],
        [("Include", "letter case"), ("tests/Build", "letter case")])
    run("naming a directory that differs only in case", [os.path.join(variant, "tests", "Build")], variant, [],
        [("tests/Build", "letter case")])
    run("a repository without src/", [], missing, ["tests/ok.py"], [("src", "does not exist")])
    run("a path outside the repository is a usage error", [root], full, None, [])
    run("a missing path is a usage error", [os.path.join(full, "src", "Gone.cpp")], full, None, [])
    unreadable = check_files([("src/Gone.cpp", CPP)], full)
    results.append(("a file that cannot be read is a problem", len(unreadable) == 1 and unreadable[0][2] == "scope", unreadable))
    linked = make(os.path.join(root, "linked"), {"src/Good.cpp": good, "tests/ok.py": py, "include/typedefs.h": b"junk"})
    moved = make(os.path.join(root, "moved"), {"elsewhere/Good.cpp": good, "tests/ok.py": py})
    try:
        os.symlink(os.path.join("..", "include"), os.path.join(linked, "src", "inclink"))
        os.symlink("Nowhere.h", os.path.join(linked, "src", "Dangling.h"))
        os.symlink("elsewhere", os.path.join(moved, "src"))
        os.symlink("linked", os.path.join(root, "alias"))
    except (OSError, NotImplementedError, AttributeError):
        print("skip  the link cases: this host cannot make a symbolic link")
    else:
        run("links under src/ are problems, not followed", [], linked, ["src/Good.cpp", "tests/ok.py"],
            [("src/inclink", "symbolic link"), ("src/Dangling.h", "symbolic link")])
        run("a path through a link resolves to where it really is", [os.path.join(linked, "src", "inclink", "typedefs.h")],
            linked, [], [], 1)
        run("naming a link is a problem", [os.path.join(linked, "src", "Dangling.h")], linked, [], [("src/Dangling.h", "symbolic link")])
        run("naming a link through another name for the repository", [os.path.join(root, "alias", "src", "Dangling.h")],
            os.path.join(root, "alias"), [], [("src/Dangling.h", "symbolic link")])
        run("src/ itself a link", [], moved, ["tests/ok.py"], [("src", "symbolic link")])
    return results


def self_test():
    """Every check_file case names the problems it must produce, so deleting any report fails a case;
    the path and tree cases do the same for choosing what to judge."""
    failures = 0
    total = 0
    fired = set()
    for name, rel, data, wanted in file_cases():
        total += 1
        got = check_file(rel, verdict_for(rel)[1], data)
        fired |= {rule for _, rule, _ in got}
        if matches(got, wanted):
            print("ok    %s" % name)
        else:
            failures += 1
            print("FAIL  %s: wanted %s" % (name, wanted or "nothing"))
            for line, rule, message in got:
                print("        %d: %s: %s" % (line, rule, message))
    for rel, wanted in path_cases():
        total += 1
        got = verdict_for(rel)[0]
        if got == wanted:
            print("ok    %s is %s" % (rel, wanted))
        else:
            failures += 1
            print("FAIL  %s: wanted %s, got %s" % (rel, wanted, got))
    for name, got, wanted in [
            ("a quoted byte is escaped", ascii_only("caf\xe9"), "caf\\xe9"),
            ("an annotation escapes its properties and its message", annotate("a,b.cpp", 3, "r8", "50% done\n"),
             "::error file=a%2Cb.cpp,line=3,title=GCS r8::50%25 done%0A")]:
        total += 1
        if got == wanted:
            print("ok    %s" % name)
        else:
            failures += 1
            print("FAIL  %s: wanted %r, got %r" % (name, wanted, got))
    for argv, wanted in parse_cases():
        total += 1
        try:
            got = parse(argv)
        except UsageError:
            got = None
        if got == wanted:
            print("ok    %s %s" % ("parses" if wanted else "refuses", " ".join(argv) or "no arguments"))
        else:
            failures += 1
            print("FAIL  %s: wanted %s, got %s" % (" ".join(argv) or "no arguments", wanted, got))
    scratch = tempfile.mkdtemp(prefix="validate_gcs_")
    try:
        for name, ok, got in tree_cases(scratch):
            total += 1
            if ok:
                print("ok    %s" % name)
                if isinstance(got, tuple) and got[1]:
                    fired.add("scope")
            else:
                failures += 1
                print("FAIL  %s: got %s" % (name, got))
    finally:
        shutil.rmtree(scratch, ignore_errors=True)
    total += 2
    silent = [rule for rule in RULES if rule not in fired]
    if silent:
        failures += 1
        print("FAIL  no case shows these rules firing: %s" % ", ".join(silent))
    if __doc__ is not None and USAGE not in __doc__:
        failures += 1
        print("FAIL  USAGE and the module docstring's usage lines have drifted apart")
    print()
    if failures:
        print("%d of %d self-test checks failed" % (failures, total))
        return 1
    print("all %d self-test checks passed" % total)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
