# RULE-DEV:r17 GCS r17's file prolog is a C block comment, which Python cannot carry. The module
# docstring below holds the same information in the form the language allows.
"""The mechanical half of GCS v1.1.4, run over src/ and tests/ -- decision D11's validator.

    python tests/validate_gcs.py                     src/ and tests/, which is what CI runs
    python tests/validate_gcs.py src/Ir.h tests/unit only what is named, inside the same scope
    python tests/validate_gcs.py --format            and clang-format 18.1.3 must be a no-op
    python tests/validate_gcs.py --self-test         every rule shown firing on a known-bad input

What a machine can check without a compiler, it checks: the r17 prolog (the standard's own regexes and
its twelve fields in order), r8's three-space indent and its ban on tabs, e2's 150 and 180 columns,
tc2's CRLF, and ASCII -- the sources carry no BOM and the project does not pass /utf-8, so a non-ASCII
byte would be read in whatever code page the compiler runs under. Everything else stays with review:
naming, the typedef lattice, whether a comment is true.

include/ is exempt, and the exemption lives here rather than in the CI invocation so that a hand run
cannot reach a different verdict (D11). The six owner-authored headers carry a nonconforming ISA token
and two pre-r17 banners that CLAUDE.md says to report, not fix, so a path under include/ is never judged
however it is named. tests/fixtures/ is input data (.editorconfig's RULE-DEV:tc2), and tests/build/,
tests/x64/ and __pycache__/ are generated, so none of those is judged either. Any other file under
src/ or tests/ whose type this script has no rules for is a failure rather than a silent pass: a new
kind of file is a decision, and this is where it is made.

Exit status: 0 clean, 1 at least one problem, 2 a usage error or nothing to check.
"""

import datetime
import io
import os
import re
import shutil
import subprocess
import sys
import tokenize

ROOT = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(ROOT)

# The two directories D11 names. A run with no arguments judges exactly these.
SCOPE = ("src", "tests")

# Never judged, whatever the command line says. The reason is printed when a named path lands here.
EXEMPT = "include"
EXEMPT_REASON = "exempt under D11 -- the owner-authored headers are reported, not fixed"
SKIPPED_DIRS = {
    "tests/fixtures": "fixture parts are input data, byte for byte (.editorconfig RULE-DEV:tc2)",
    "tests/build": "generated by make_fixtures.py",
    "tests/x64": "build output of the unit-test project",
}
SKIPPED_NAMES = {"__pycache__": "generated by CPython"}
SKIPPED_SUFFIXES = {".vcxproj.user": "Visual Studio's per-user settings"}

# What each kind of file is held to. C and C++ carry every rule. Python carries a tagged r17 deviation
# and a tagged four-space indent (.editorconfig's RULE-DEV:r8), so its prolog check is the tag itself.
# MSBuild XML is written and rewritten by Visual Studio, two-space indented, with <Import> elements of
# 179 columns it puts back on every save: r8 does not reach it and e2's "unless splitting is
# impractical" is exactly its case, so only the hard cap binds -- RULE-DEV:r8,e2 for IDE-owned XML.
CPP = "C++"
PYTHON = "Python"
MSBUILD = "MSBuild"
CLASSES = {
    ".c": CPP, ".cpp": CPP, ".h": CPP, ".hpp": CPP, ".inl": CPP,
    ".py": PYTHON,
    ".vcxproj": MSBUILD, ".filters": MSBUILD, ".props": MSBUILD,
}

SOFT_WIDTH = 150
HARD_WIDTH = 180
WIDTH_MARK = {CPP: " // WIDTH-EXEMPT", PYTHON: " # WIDTH-EXEMPT"}
PYTHON_TAG = "# RULE-DEV:r17 "
PYTHON_STEP = 4
CPP_STEP = 3
CLANG_FORMAT_VERSION = "18.1.3"
UTF8_BOM = b"\xef\xbb\xbf"

# r17's "Validation (minimal)", verbatim from GDC_GCS_v1_1_4.md.
PROLOG_OPEN = re.compile(r"^\s*/\*\s*$")
PROLOG_CLOSE = re.compile(r"^\s*\*/\s*$")
PROLOG_INNER = re.compile(r"^ \*(| .{0,147}| .{0,161} // WIDTH-EXEMPT)$")
PROLOG_DATE = re.compile(r"^ \* (Created|Last Modified): \d{4}-\d{2}-\d{2}$")
PROLOG_VERSION = re.compile(r"^ \* Version: v\d+\.\d+(\.\d+)?$")
PROLOG_LICENSE = re.compile(r"^ \* License: [A-Za-z0-9.+-]+  Copyright: .+$")
ISA_TOKENS = ("Scalar", "SSE4.2", "AVX2", "AVX-512")
THREAD_SAFETY = ("N/A", "Reentrant", "MT-safe")

# r17's required fields, lettered A to L, in the order the standard lists them. Only these three may
# run onto a continuation line: To Do by r17's own words, and the two lists beside it.
FIELDS = ("File", "Version", "Owner", "Created", "Last Modified", "Description", "To Do", "Dependencies",
          "ISA", "Thread-safety", "Reviewers", "License")
MULTILINE = ("To Do", "Dependencies", "Reviewers")
PROLOG_SEARCH = 200

# Every rule a problem can be reported under, so the self-test can prove each one still fires.
RULES = ("r17", "r8", "e2", "tc2", "ascii", "en3", "scope")

# The formatter's findings are reported under tc1, the rule .clang-format implements. They need the pinned
# binary, so the self-test cannot fire them and RULES does not list them.
FORMAT_RULE = "tc1"


# ---------------------------------------------------------------------------------------------------
# Choosing what to judge


def relative(path):
    """Returns the path relative to the repository with forward slashes, or None when it is outside it."""
    try:
        rel = os.path.relpath(os.path.abspath(path), REPO)
    except ValueError:
        return None
    rel = rel.replace(os.sep, "/")
    if rel == ".." or rel.startswith("../"):
        return None
    return rel


def same(a, b):
    return os.path.normcase(a) == os.path.normcase(b)


def verdict_for(rel):
    """Says what happens to one repository-relative path: (kind, reason). kind is 'judge', 'skip',
    'exempt', 'outside' or 'unknown', and reason is the file class for 'judge'."""
    parts = rel.split("/")
    if same(parts[0], EXEMPT):
        return "exempt", EXEMPT_REASON
    if not any(same(parts[0], top) for top in SCOPE):
        return "outside", "outside D11's scope, which is %s" % " and ".join(s + "/" for s in SCOPE)
    for prefix, reason in SKIPPED_DIRS.items():
        size = len(prefix.split("/"))
        if len(parts) >= size and same("/".join(parts[:size]), prefix):
            return "skip", reason
    for part in parts:
        if part in SKIPPED_NAMES:
            return "skip", SKIPPED_NAMES[part]
    for suffix, reason in SKIPPED_SUFFIXES.items():
        if rel.lower().endswith(suffix):
            return "skip", reason
    kind = CLASSES.get(os.path.splitext(rel)[1].lower())
    if kind is None:
        return "unknown", "no rules are defined for this type of file"
    return "judge", kind


def walk(rel_dir):
    """Every file under one repository-relative directory, sorted, pruning what is never judged."""
    found = []
    for here, dirs, files in os.walk(os.path.join(REPO, rel_dir)):
        base = relative(here)
        dirs[:] = sorted(d for d in dirs if verdict_for(base + "/" + d + "/x")[0] not in ("skip", "exempt"))
        found.extend(base + "/" + name for name in sorted(files))
    return found


def judge(candidates, files, problems):
    """Adds each candidate the rules reach to files, and each one no class covers to problems. Returns
    how many were judged, which a default run uses to refuse a vacuous pass."""
    count = 0
    for rel in candidates:
        kind, reason = verdict_for(rel)
        if kind == "judge":
            count += 1
            if rel not in [f for f, _ in files]:
                files.append((rel, reason))
        elif kind == "unknown":
            problems.append((rel, 0, "scope", reason + "; give it a class in validate_gcs.py, or move it"))
    return count


def select(args, notes):
    """Turns the command line into (files, problems): the files to judge, in order, and any path that
    is a problem in itself. A named path that is never judged is explained in notes instead."""
    files = []
    problems = []
    if not args:
        for top in SCOPE:
            if judge(walk(top), files, problems) == 0:
                problems.append((top + "/", 0, "scope", "nothing here to judge, and D11 names this directory"))
        return files, problems
    for name in args:
        full = os.path.abspath(name)
        if not os.path.exists(full):
            raise UsageError("no such file or directory: %s" % name)
        rel = relative(full)
        if rel is None:
            notes.append("%s: not judged -- outside the repository" % name)
            continue
        if rel == ".":
            notes.append("%s: narrowed to %s" % (name, " and ".join(top + "/" for top in SCOPE)))
            notes.append("%s/: not judged -- %s" % (EXEMPT, EXEMPT_REASON))
            for top in SCOPE:
                judge(walk(top), files, problems)
            continue
        directory = os.path.isdir(full)
        kind, reason = verdict_for(rel + "/x" if directory else rel)
        if kind in ("exempt", "outside", "skip"):
            notes.append("%s: not judged -- %s" % (rel, reason))
            continue
        judge(walk(rel) if directory else [rel], files, problems)
    return files, problems


class UsageError(Exception):
    pass


# ---------------------------------------------------------------------------------------------------
# Rules every file is held to


def split_lines(data):
    """Splits decoded text into lines without their terminators. Latin-1 maps each byte to one
    character, so a column is a byte; a byte that is not ASCII is the ASCII rule's to report."""
    text = data.decode("latin-1")
    lines = text.split("\n")
    if lines and lines[-1] == "":
        lines.pop()
    return [line[:-1] if line.endswith("\r") else line for line in lines]


def line_of(data, offset):
    return data.count(b"\n", 0, offset) + 1


def check_bytes(data, kind):
    """tc2's CRLF, r8's no tabs, and ASCII. Each rule reports its first offence and how many there
    are, because a file saved with the wrong settings breaks one of them on every line."""
    problems = []
    body = data
    start = 0
    if kind == MSBUILD and data.startswith(UTF8_BOM):
        start = len(UTF8_BOM)

    def report(rule, offsets, what):
        if offsets:
            more = "" if len(offsets) == 1 else " (%d in all)" % len(offsets)
            problems.append((line_of(body, offsets[0]), rule, what + more))

    bare_lf = [m.start() for m in re.finditer(rb"(?<!\r)\n", body)]
    bare_cr = [m.start() for m in re.finditer(rb"\r(?!\n)", body)]
    report("tc2", bare_lf, "a line ends LF rather than CRLF")
    report("tc2", bare_cr, "a carriage return is not followed by a line feed")
    if body and not body.endswith(b"\n"):
        problems.append((line_of(body, len(body)), "tc2", "the last line has no CRLF after it"))
    tabs = [m.start() for m in re.finditer(rb"\t", body)]
    report("r8", tabs, "a tab character; indent with three spaces")
    wide = [i for i in range(start, len(body)) if body[i] > 0x7F]
    if wide:
        report("ascii", wide, "byte 0x%02X is not ASCII" % body[wide[0]])
    controls = [i for i in range(len(body)) if (body[i] < 0x20 and body[i] not in b"\t\r\n") or body[i] == 0x7F]
    if controls:
        report("ascii", controls, "control byte 0x%02X" % body[controls[0]])
    return problems


def check_width(lines, kind, skip_until=-1):
    """e2: 150 columns unless splitting is impractical, and 180 whatever. A C++ or Python line may take
    the extra thirty only by saying so with r17's own WIDTH-EXEMPT mark; project XML is IDE-owned and
    held to the hard cap alone."""
    problems = []
    mark = WIDTH_MARK.get(kind)
    for index, line in enumerate(lines):
        if index <= skip_until:
            continue
        width = len(line)
        if index == 0 and line.startswith("\xef\xbb\xbf"):
            width -= 3
        if width > HARD_WIDTH:
            problems.append((index + 1, "e2", "%d columns is past the hard cap of %d" % (width, HARD_WIDTH)))
        elif width > SOFT_WIDTH and mark is not None and not line.endswith(mark):
            problems.append((index + 1, "e2", "%d columns; wrap at %d, or end the line with '%s' if it cannot be split"
                             % (width, SOFT_WIDTH, mark.strip())))
    return problems


# ---------------------------------------------------------------------------------------------------
# r17: the file prolog


def check_prolog(lines, filename):
    """Returns (problems, closing line index or -1). The regexes are the standard's; the field walk is
    the rest of r17's text made mechanical: twelve fields, once each, A to L, To Do numbered 1), 2) ...
    and every continuation aligned under the value it continues."""
    problems = []
    if not lines or not PROLOG_OPEN.match(lines[0]):
        return [(1, "r17", "the file must open with the prolog's '/*' line")], -1
    close = -1
    for index in range(1, min(len(lines), PROLOG_SEARCH)):
        if PROLOG_CLOSE.match(lines[index]):
            close = index
            break
    if close < 0:
        return [(1, "r17", "the prolog's closing ' */' line was not found")], -1

    fields = []
    current = None
    for index in range(1, close):
        line = lines[index]
        number = index + 1
        if line == " *":
            current = None
            continue
        if line.rstrip(" ") == " *":
            # The regex lets ' * ' through as a content line of nothing; r17's prose does not.
            problems.append((number, "r17", "a blank prolog line is exactly ' *', with nothing after it"))
            current = None
            continue
        if not PROLOG_INNER.match(line):
            if line.startswith(" * "):
                problems.append((number, "r17", "a prolog line is %d columns; wrap at 150, or end it with "
                                 "'%s' within 180" % (len(line), WIDTH_MARK[CPP].strip())))
            else:
                problems.append((number, "r17", "a prolog line starts with exactly ' * ', or is exactly ' *'"))
            current = None
            continue
        if line.endswith(WIDTH_MARK[CPP]):
            line = line[:-len(WIDTH_MARK[CPP])]
        text = line[3:]
        if re.match(r"\s*History\s*:", text):
            problems.append((number, "r17", "no 'History:' in a prolog; history belongs in CHANGELOG.md (c1)"))
            current = None
            continue
        label = next((f for f in FIELDS if text.startswith(f + ":")), None)
        if label is not None:
            value = text[len(label) + 1:]
            if not value.startswith(" ") or value.startswith("  ") or not value.strip():
                problems.append((number, "r17", "'%s:' takes one space and then its value" % label))
            current = {"label": label, "line": number, "column": 3 + len(label) + 2,
                       "value": value[1:].rstrip(), "more": []}
            fields.append(current)
        elif text.startswith(" "):
            if current is None or current["label"] not in MULTILINE:
                what = "a field" if current is None else "'%s:'" % current["label"]
                problems.append((number, "r17", "a continuation line, but %s takes one line" % what))
                current = None
            else:
                body = line[2:]
                current["more"].append((number, 2 + len(body) - len(body.lstrip(" ")), body.strip()))
        else:
            problems.append((number, "r17", "not one of r17's twelve fields: %s" % text.split(":")[0][:40]))
            current = None

    seen = [f["label"] for f in fields]
    for label in FIELDS:
        if seen.count(label) == 0:
            problems.append((close + 1, "r17", "the '%s:' field is missing" % label))
        elif seen.count(label) > 1:
            later = [f["line"] for f in fields if f["label"] == label][1]
            problems.append((later, "r17", "'%s:' appears %d times" % (label, seen.count(label))))
    order = [FIELDS.index(label) for label in seen]
    for position in range(1, len(order)):
        if order[position] < order[position - 1]:
            problems.append((fields[position]["line"], "r17", "'%s:' comes after '%s:'; r17 orders the fields A to L"
                             % (fields[position]["label"], fields[position - 1]["label"])))
            break

    first = {}
    for field in fields:
        first.setdefault(field["label"], field)
    for field in first.values():
        problems.extend(check_field(field, lines, filename))

    created = first.get("Created")
    modified = first.get("Last Modified")
    if created and modified:
        try:
            if datetime.date.fromisoformat(created["value"]) > datetime.date.fromisoformat(modified["value"]):
                problems.append((modified["line"], "r17", "'Last Modified:' is earlier than 'Created:'"))
        except ValueError:
            pass
    return problems, close


def check_field(field, lines, filename):
    """One field's own rule. The full-line regexes are r17's; the rest is the field's text."""
    label = field["label"]
    value = field["value"]
    number = field["line"]
    line = lines[number - 1]
    problems = []

    def fail(message, at=number):
        problems.append((at, "r17", message))

    if label == "File" and value != filename:
        fail("'File:' says %s, but the file is %s" % (value, filename))
    elif label == "Version" and not PROLOG_VERSION.match(line):
        fail("'Version:' is vMAJOR.MINOR or vMAJOR.MINOR.PATCH")
    elif label in ("Created", "Last Modified"):
        if not PROLOG_DATE.match(line):
            fail("'%s:' is a YYYY-MM-DD date and nothing else" % label)
        else:
            try:
                datetime.date.fromisoformat(value)
            except ValueError:
                fail("'%s:' is not a calendar date: %s" % (label, value))
    elif label == "To Do":
        item = re.match(r"(\d+)\) \S", value)
        if not item or item.group(1) != "1":
            fail("'To Do:' opens with item 1), on the label's own line")
        expected = 2
        text_column = field["column"] + len("1) ")
        for at, column, content in field["more"]:
            numbered = re.match(r"(\d+)\) \S", content)
            if column == field["column"] and numbered:
                if int(numbered.group(1)) != expected:
                    fail("To Do item %s) should be %d)" % (numbered.group(1), expected), at)
                expected = int(numbered.group(1)) + 1
                text_column = column + len(numbered.group(1)) + 2
            elif column == field["column"]:
                fail("a To Do line at the value column starts a numbered item, %d)" % expected, at)
            elif column != text_column:
                fail("a To Do continuation aligns under its item's text, at column %d, not %d" % (text_column + 1, column + 1),
                     at)
    elif label in ("Dependencies", "Reviewers"):
        for at, column, content in field["more"]:
            if column != field["column"]:
                fail("a '%s:' continuation aligns under the value, at column %d, not %d" % (label, field["column"] + 1, column + 1),
                     at)
        if label == "Dependencies":
            joined = " ".join([value] + [content for _, _, content in field["more"]])
            if joined != "None" and not re.fullmatch(r"[^,\s]([^,]*[^,\s])?(, [^,\s]([^,]*[^,\s])?)*", joined):
                fail("'Dependencies:' is None or a comma-separated list")
    elif label == "ISA":
        tokens = value.split(" | ")
        if any(token not in ISA_TOKENS for token in tokens):
            fail("'ISA:' tokens come from {%s}, separated by ' | '" % ", ".join(ISA_TOKENS))
        elif len(set(tokens)) != len(tokens):
            fail("'ISA:' names a token twice")
    elif label == "Thread-safety" and value not in THREAD_SAFETY:
        fail("'Thread-safety:' is one of %s" % ", ".join(THREAD_SAFETY))
    elif label == "License" and not PROLOG_LICENSE.match(line):
        fail("'License:' is an SPDX id, exactly two spaces, then 'Copyright: <holder>'")
    return problems


# ---------------------------------------------------------------------------------------------------
# r8: three-space indentation in C and C++


def blank_literals(lines):
    """Returns each line's code with comments removed, string and character literals reduced to empty
    quotes and preprocessor lines emptied, carrying block comments and raw strings across lines. What is
    left is enough to see braces and parentheses, which is all the indent check needs."""
    code = []
    in_comment = False
    raw_end = None
    continued = False
    for line in lines:
        if not in_comment and raw_end is None and (continued or line.lstrip(" ").startswith("#")):
            continued = line.endswith("\\")
            code.append("")
            continue
        out = []
        i = 0
        while i < len(line):
            if in_comment:
                end = line.find("*/", i)
                if end < 0:
                    i = len(line)
                    break
                in_comment = False
                out.append(" ")
                i = end + 2
                continue
            if raw_end is not None:
                end = line.find(raw_end, i)
                if end < 0:
                    i = len(line)
                    break
                i = end + len(raw_end)
                raw_end = None
                out.append('""')
                continue
            c = line[i]
            if c == "/" and line.startswith("//", i):
                break
            if c == "/" and line.startswith("/*", i):
                in_comment = True
                i += 2
                continue
            if c == '"':
                prefix = re.search(r"(?:^|[^A-Za-z0-9_])(?:u8|u|U|L)?R$", line[:i])
                if prefix:
                    opening = line.find("(", i)
                    if opening >= 0:
                        raw_end = ")" + line[i + 1:opening] + '"'
                        i = opening + 1
                        continue
                i += 1
                while i < len(line) and line[i] != '"':
                    i += 2 if line[i] == "\\" else 1
                out.append('""')
                i += 1
                continue
            if c == "'":
                # A digit separator, 1'000 or 0xFF'FF, sits inside a number; L'0' and u8'a' are prefixed
                # character literals, whose token starts with a letter rather than a digit.
                token = re.search(r"[A-Za-z0-9_.']*$", line[:i]).group(0)
                if token[:1].isdigit() and i + 1 < len(line) and line[i + 1].isalnum():
                    i += 1
                    continue
                i += 1
                while i < len(line) and line[i] != "'":
                    i += 2 if line[i] == "\\" else 1
                out.append("''")
                i += 1
                continue
            out.append(c)
            i += 1
        code.append("".join(out))
    return code


def brace_kind(before, previous_end, inside_initializer):
    """'init' for a braced initializer, whose rows clang-format aligns rather than indents; 'block'
    for anything whose body is indented one step: a function, a control statement, a struct or an enum."""
    if inside_initializer:
        return "init"
    text = before.rstrip()
    last = text[-1:] if text else previous_end
    if last in ("=", "(", ",", "[", "{", "?") or re.search(r"(^|[^A-Za-z0-9_])return$", text):
        return "init"
    return "block"


def check_indent(lines):
    """r8, made mechanical over the brace structure rather than over every line, because a continuation
    line is aligned rather than indented and belongs to no step. Every statement that starts inside a
    block starts exactly three spaces past the statement that opened it, a closing brace lines up with
    that statement, and a statement at file scope starts in column one. The exceptions are the ones
    .clang-format itself makes: a case label sits at its switch (IndentCaseLabels is LLVM's false), an
    access specifier one column in (AccessModifierOffset -2 on a three-space step), and an extern "C"
    body not indented at all."""
    problems = []
    code = blank_literals(lines)
    stack = []
    depth = 0
    previous_end = ""
    statement = 0
    statement_text = ""
    for index, raw in enumerate(lines):
        text = code[index].strip()
        if not text:
            continue
        indent = len(raw) - len(raw.lstrip(" "))
        top = stack[-1] if stack else None
        in_enum = top is not None and top["enum"]
        starts = depth == 0 and (previous_end in ("", ";", "{", "}", ":") or (previous_end == "," and in_enum))
        if starts and not text.startswith("}"):
            statement = indent
            statement_text = text
            expected = None
            if top is None:
                expected = 0
            elif top["kind"] == "init":
                expected = None
            elif top["extern"]:
                expected = top["indent"]
            elif top["switch"] and re.match(r"(case\b.*|default\s*):", text):
                expected = top["indent"]
            elif re.match(r"(public|private|protected)\s*:", text):
                expected = top["indent"] + CPP_STEP - 2
            else:
                expected = top["indent"] + CPP_STEP
            if expected is not None and indent != expected:
                problems.append((index + 1, "r8", "this statement starts at column %d; its block puts it at column %d"
                                 % (indent + 1, expected + 1)))
        line_code = code[index]
        first = len(line_code) - len(line_code.lstrip(" "))
        for position, c in enumerate(line_code):
            if c in "([":
                depth += 1
            elif c in ")]":
                depth = max(0, depth - 1)
            elif c == "{":
                kind = brace_kind(line_code[:position], previous_end, bool(stack) and stack[-1]["kind"] == "init")
                owner = statement_text
                stack.append({"kind": kind, "indent": statement,
                              "switch": kind == "block" and bool(re.match(r"switch\s*\(", owner)),
                              "extern": kind == "block" and owner.startswith('extern ""'),
                              "enum": kind == "block" and bool(re.search(r"(^|\s)enum(\s|$)", owner))})
            elif c == "}":
                if not stack:
                    problems.append((index + 1, "r8", "a closing brace with no opening brace before it"))
                    continue
                entry = stack.pop()
                if position == first:
                    if entry["kind"] == "block" and indent != entry["indent"]:
                        problems.append((index + 1, "r8", "this closing brace is at column %d; the statement it closes starts "
                                         "at column %d" % (indent + 1, entry["indent"] + 1)))
                    statement = entry["indent"]
                    statement_text = text
        previous_end = text[-1]
    return problems


# ---------------------------------------------------------------------------------------------------
# Python: the tagged deviations, and the four-space step they allow


def check_python(data):
    """en3: r17's prolog cannot be written in Python, so the file says so on its first line instead of
    deviating silently. r8's exemption is .editorconfig's four spaces, so every indent steps by four."""
    problems = []
    text = data.decode("latin-1").replace("\r\n", "\n")
    if not text.startswith(PYTHON_TAG):
        problems.append((1, "en3", "a Python file opens with '%s' and its reason, standing in for the r17 prolog"
                         % PYTHON_TAG.strip()))
    widths = [0]
    try:
        for token in tokenize.generate_tokens(io.StringIO(text).readline):
            if token.type == tokenize.INDENT:
                width = len(token.string)
                if width - widths[-1] != PYTHON_STEP:
                    problems.append((token.start[0], "r8", "this block is indented %d past its parent; Python steps by %d "
                                     "(.editorconfig RULE-DEV:r8)" % (width - widths[-1], PYTHON_STEP)))
                widths.append(width)
            elif token.type == tokenize.DEDENT and len(widths) > 1:
                widths.pop()
    except (tokenize.TokenError, IndentationError, SyntaxError) as error:
        problems.append((0, "r8", "cannot tokenize this file: %s" % error))
    return problems


# ---------------------------------------------------------------------------------------------------
# One file


def check_file(rel, kind, data):
    """Every rule the file's class carries, as (line, rule, message) tuples sorted by line."""
    problems = check_bytes(data, kind)
    lines = split_lines(data)
    if kind == CPP:
        prolog, close = check_prolog(lines, rel.split("/")[-1])
        problems.extend(prolog)
        problems.extend(check_width(lines, kind, close))
        problems.extend(check_indent(lines))
    elif kind == PYTHON:
        problems.extend(check_width(lines, kind))
        problems.extend(check_python(data))
    else:
        problems.extend(check_width(lines, kind))
    return sorted(problems, key=lambda p: (p[0], p[1]))


# ---------------------------------------------------------------------------------------------------
# clang-format, pinned


def format_check(files, exe):
    """Runs clang-format in dry-run over the C++ files judged. The verdict is pinned to one release,
    because two releases can format one file two ways and CI must not change its mind when a runner
    image does; 18.1.3 is what every session since M1 verified the tree against."""
    found = shutil.which(exe) or (exe if os.path.isfile(exe) else None)
    if found is None:
        return [("clang-format", 0, FORMAT_RULE, "clang-format was not found; pip install clang-format==%s, or pass "
                 "--clang-format <path>" % CLANG_FORMAT_VERSION)]
    version = subprocess.run([found, "--version"], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, cwd=REPO)
    match = re.search(r"clang-format version (\d+\.\d+\.\d+)", version.stdout.decode("utf-8", "replace"))
    if not match or match.group(1) != CLANG_FORMAT_VERSION:
        return [("clang-format", 0, FORMAT_RULE, "the formatter verdict is pinned to clang-format %s, and %s is %s"
                 % (CLANG_FORMAT_VERSION, found, match.group(1) if match else "an unknown version"))]
    cpp = [rel for rel, kind in files if kind == CPP]
    problems = []
    for start in range(0, len(cpp), 40):
        batch = cpp[start:start + 40]
        done = subprocess.run([found, "--dry-run", "--Werror", "--style=file"] + batch, stdout=subprocess.PIPE,
                              stderr=subprocess.STDOUT, cwd=REPO)
        if done.returncode != 0:
            output = done.stdout.decode("utf-8", "replace")
            reported = set()
            for hit in re.finditer(r"^(.+?):(\d+):\d+: (?:error|warning): (.*)$", output, re.M):
                where = relative(os.path.join(REPO, hit.group(1))) or hit.group(1)
                if (where, hit.group(2)) not in reported:
                    reported.add((where, hit.group(2)))
                    problems.append((where, int(hit.group(2)), FORMAT_RULE, "clang-format would change this line"))
            if not reported:
                problems.append((" ".join(batch), 0, FORMAT_RULE, "clang-format failed: %s" % output.strip()[:300]))
    return problems


# ---------------------------------------------------------------------------------------------------
# Reporting and the command line


def annotate(rel, line, rule, message):
    """A GitHub Actions error annotation, so a failure lands on the line in the pull request's diff."""
    def escape(text, extra=""):
        text = text.replace("%", "%25").replace("\r", "%0D").replace("\n", "%0A")
        for c in extra:
            text = text.replace(c, "%%%02X" % ord(c))
        return text
    where = "file=%s" % escape(rel, ":,")
    if line:
        where += ",line=%d" % line
    return "::error %s,title=%s::%s" % (where, escape("GCS " + rule, ":,"), escape(message))


def show(problems):
    on_github = os.environ.get("GITHUB_ACTIONS") == "true"
    for rel, line, rule, message in problems:
        print("%s:%s %s: %s" % (rel, "%d:" % line if line else "", rule, message))
        if on_github:
            print(annotate(rel, line, rule, message))


def main(argv):
    args = list(argv)
    want_format = "--format" in args
    exe = "clang-format"
    if "--self-test" in args:
        return self_test()
    if "--clang-format" in args:
        at = args.index("--clang-format")
        if at + 1 >= len(args):
            print("validate_gcs: --clang-format needs a path")
            return 2
        exe = args[at + 1]
        del args[at:at + 2]
    args = [a for a in args if a != "--format"]
    unknown = [a for a in args if a.startswith("--")]
    if unknown:
        print("validate_gcs: unknown option %s" % unknown[0])
        print(__doc__.split("\n\n")[1])
        return 2

    notes = []
    try:
        files, problems = select(args, notes)
    except UsageError as error:
        print("validate_gcs: %s" % error)
        return 2
    for note in notes:
        print(note)
    if not files and not problems:
        print("validate_gcs: nothing to check")
        return 2

    for rel, kind in files:
        with open(os.path.join(REPO, rel), "rb") as handle:
            data = handle.read()
        problems.extend((rel, line, rule, message) for line, rule, message in check_file(rel, kind, data))
    if want_format:
        problems.extend(format_check(files, exe))
    show(problems)
    touched = len({p[0] for p in problems})
    print("validate_gcs: %d file%s judged, %d problem%s in %d file%s" % (
        len(files), "" if len(files) == 1 else "s", len(problems), "" if len(problems) == 1 else "s",
        touched, "" if touched == 1 else "s"))
    return 1 if problems else 0


# ---------------------------------------------------------------------------------------------------
# The self-test: every rule, shown firing


GOOD_PROLOG = [
    "/*",
    " * File: Good.cpp",
    " * Version: v0.1.0",
    " * Owner: David William Bull",
    " * Created: 2026-09-25",
    " * Last Modified: 2026-09-25",
    " * Description: A file every rule accepts, which each case below breaks in one place.",
    " * To Do: 1) Stay clean.",
    " *        2) Keep a continuation aligned under the",
    " *           item it continues.",
    " * Dependencies: typedefs.h, memory management.h,",
    " *               stdio.h",
    " * ISA: Scalar | AVX2",
    " * Thread-safety: Reentrant",
    " * Reviewers: David William Bull",
    " * License: MIT  Copyright: David William Bull",
    " */",
]
GOOD_BODY = [
    "#include \"typedefs.h\"",
    "#define PAIR(a, b) { a, \\",
    "                     b }",
    "",
    "static const ui32 TABLE[] = {",
    "    1, 2,   // a row clang-format aligns rather than indents",
    "};",
    "",
    "enum COLOUR : ui8 {",
    "   COLOUR_RED,",
    "   COLOUR_BLUE,",
    "};",
    "",
    "si32 Good(csi32 a,",
    "          csi32 b) {",
    "   if(a) {",
    "      switch(b) {",
    "      case 1: return 1;",
    "      default: break;",
    "      }",
    "   } else {",
    "      Call(\"a { brace in a string\", '{');   // and { one in a comment",
    "      Call(L'0', L'{', R\"x(\")\" { \")x\", u8R\"(})\");   // each literal hides a brace from a wrong lexer",
    "      Call(1'000, '}');",
    "   }",
    "   /* a block comment { with a brace",
    "      that runs over two lines */",
    "   return b;",
    "}",
]


def cpp(lines):
    return ("\r\n".join(lines) + "\r\n").encode("latin-1")


def replaced(lines, old, new):
    out = list(lines)
    out[out.index(old)] = new
    return out


def self_test():
    """Each case is a file that breaks exactly one rule, and the rule it must be reported under."""
    good = GOOD_PROLOG + GOOD_BODY
    lead = "   return b; // "
    mark = WIDTH_MARK[CPP]
    at_limit = lead + "x" * (SOFT_WIDTH - len(lead))
    too_wide = lead + "x" * (SOFT_WIDTH + 1 - len(lead))
    exempt_wide = lead + "x" * (HARD_WIDTH - len(lead) - len(mark)) + mark
    over_cap = lead + "x" * (HARD_WIDTH + 1 - len(lead) - len(mark)) + mark
    xml_lead = "  <Import Project=\""
    xml_tail = "\" />"
    cases = [
        ("a clean C++ file", "src/Good.cpp", cpp(good), set()),
        ("a tab", "src/Good.cpp", cpp(replaced(good, "   return b;", "\treturn b;")), {"r8"}),
        ("a byte that is not ASCII", "src/Good.cpp",
         cpp(replaced(good, "   return b;", "   return b; // caf\xe9")), {"ascii"}),
        ("a control byte", "src/Good.cpp", cpp(replaced(good, "   return b;", "   return b;\x0c")), {"ascii"}),
        ("an LF line ending", "src/Good.cpp", cpp(good).replace(b"return b;\r\n", b"return b;\n"), {"tc2"}),
        ("no CRLF after the last line", "src/Good.cpp", cpp(good)[:-2], {"tc2"}),
        ("150 columns", "src/Good.cpp", cpp(replaced(good, "   return b;", at_limit)), set()),
        ("151 columns", "src/Good.cpp", cpp(replaced(good, "   return b;", too_wide)), {"e2"}),
        ("180 columns marked WIDTH-EXEMPT", "src/Good.cpp", cpp(replaced(good, "   return b;", exempt_wide)), set()),
        ("181 columns, even marked", "src/Good.cpp", cpp(replaced(good, "   return b;", over_cap)), {"e2"}),
        ("no prolog", "src/Good.cpp", cpp(GOOD_BODY), {"r17"}),
        ("one space before Copyright:", "src/Good.cpp",
         cpp(replaced(good, " * License: MIT  Copyright: David William Bull",
                      " * License: MIT Copyright: David William Bull")), {"r17"}),
        ("the ISA token typedefs.h gets wrong", "src/Good.cpp",
         cpp(replaced(good, " * ISA: Scalar | AVX2", " * ISA: Scalar | AVX512")), {"r17"}),
        ("an ISA separator without spaces", "src/Good.cpp",
         cpp(replaced(good, " * ISA: Scalar | AVX2", " * ISA: Scalar|AVX2")), {"r17"}),
        ("a Thread-safety outside the three tokens", "src/Good.cpp",
         cpp(replaced(good, " * Thread-safety: Reentrant", " * Thread-safety: Thread-compatible")), {"r17"}),
        ("a History: field", "src/Good.cpp",
         cpp(replaced(good, " * Reviewers: David William Bull", " * History: 2026-09-25 created")), {"r17"}),
        ("a File: naming another file", "src/Good.cpp",
         cpp(replaced(good, " * File: Good.cpp", " * File: Other.cpp")), {"r17"}),
        ("a missing field", "src/Good.cpp",
         cpp([line for line in good if not line.startswith(" * Owner:")]), {"r17"}),
        ("two fields out of order", "src/Good.cpp",
         cpp(replaced(replaced(good, " * Version: v0.1.0", " * Owner: X"), " * Owner: David William Bull",
                      " * Version: v0.1.0")), {"r17"}),
        ("a date that is not a date", "src/Good.cpp",
         cpp(replaced(good, " * Created: 2026-09-25", " * Created: 2026-02-30")), {"r17"}),
        ("modified before it was created", "src/Good.cpp",
         cpp(replaced(good, " * Created: 2026-09-25", " * Created: 2026-09-26")), {"r17"}),
        ("a version without its v", "src/Good.cpp",
         cpp(replaced(good, " * Version: v0.1.0", " * Version: 0.1.0")), {"r17"}),
        ("a To Do item misnumbered", "src/Good.cpp",
         cpp(replaced(good, " *        2) Keep a continuation aligned under the",
                      " *        3) Keep a continuation aligned under the")), {"r17"}),
        ("a To Do continuation misaligned", "src/Good.cpp",
         cpp(replaced(good, " *           item it continues.", " *          item it continues.")), {"r17"}),
        ("a Dependencies continuation misaligned", "src/Good.cpp",
         cpp(replaced(good, " *               stdio.h", " *              stdio.h")), {"r17"}),
        ("a continuation of a one-line field", "src/Good.cpp",
         cpp(replaced(good, " * ISA: Scalar | AVX2", " * ISA: Scalar |\r\n *      AVX2")), {"r17"}),
        ("a blank prolog line with a trailing space", "src/Good.cpp",
         cpp(replaced(good, " * Thread-safety: Reentrant", " * Thread-safety: Reentrant\r\n * ")), {"r17"}),
        ("a prolog line without its space", "src/Good.cpp",
         cpp(replaced(good, " * Reviewers: David William Bull", " *Reviewers: David William Bull")), {"r17"}),
        ("a four-space block", "src/Good.cpp",
         cpp(replaced(good, "   return b;", "    return b;")), {"r8"}),
        ("a two-space block", "src/Good.cpp",
         cpp(replaced(good, "      Call(\"a { brace in a string\", '{');   // and { one in a comment",
                      "     Call(\"a { brace in a string\", '{');   // and { one in a comment")), {"r8"}),
        ("a closing brace out of line", "src/Good.cpp", cpp(replaced(good, "   } else {", "    } else {")), {"r8"}),
        ("an indented statement at file scope", "src/Good.cpp",
         cpp(replaced(good, "si32 Good(csi32 a,", "   si32 Good(csi32 a,")), {"r8"}),
        ("an enum member out of step", "src/Good.cpp", cpp(replaced(good, "   COLOUR_BLUE,", "    COLOUR_BLUE,")), {"r8"}),
        ("a Python file with its tag", "tests/good.py",
         cpp([PYTHON_TAG + "the reason", "def f():", "    return 1"]), set()),
        ("a Python file without its tag", "tests/good.py", cpp(["def f():", "    return 1"]), {"en3"}),
        ("a Python block indented three", "tests/good.py",
         cpp([PYTHON_TAG + "the reason", "def f():", "   return 1"]), {"r8"}),
        ("project XML at 180 columns, with a BOM", "tests/X.vcxproj",
         UTF8_BOM + cpp(["<Project>", xml_lead + "x" * (HARD_WIDTH - len(xml_lead) - len(xml_tail)) + xml_tail,
                         "</Project>"]), set()),
        ("project XML at 181 columns", "tests/X.vcxproj",
         cpp(["<Project>", xml_lead + "x" * (HARD_WIDTH + 1 - len(xml_lead) - len(xml_tail)) + xml_tail,
              "</Project>"]), {"e2"}),
    ]
    failures = 0
    fired = set()
    for name, rel, data, wanted in cases:
        kind = verdict_for(rel)[1]
        got = check_file(rel, kind, data)
        rules = {rule for _, rule, _ in got}
        fired |= rules
        if rules == wanted:
            print("ok    %s" % name)
        else:
            failures += 1
            print("FAIL  %s: wanted %s, got %s" % (name, sorted(wanted) or "nothing", sorted(rules) or "nothing"))
            for line, rule, message in got:
                print("        %d: %s: %s" % (line, rule, message))

    paths = [
        ("include/typedefs.h", "exempt"), ("Include/typedefs.h", "exempt" if os.name == "nt" else "outside"),
        ("include", "exempt"), ("src/Ir.h", "judge"), ("tests/unit/Check.h", "judge"),
        ("tests/fixtures/minimal/src/word/document.xml", "skip"), ("tests/build/minimal.docx", "skip"),
        ("tests/x64/Release/DOCXtoMD.Tests.exe", "skip"), ("tests/__pycache__/make_fixtures.cpython-311.pyc", "skip"),
        ("tests/DOCXtoMD.Tests.vcxproj.user", "skip"), ("tests/notes.txt", "unknown"), ("docs/CONVERSION_REFERENCE.md", "outside"),
        ("DOCXtoMD.vcxproj", "outside"), ("src/Upper.CPP", "judge"),
    ]
    for rel, wanted in paths:
        got = verdict_for(rel)[0]
        if got == "unknown":
            fired.add("scope")
        if got == wanted:
            print("ok    %s is %s" % (rel, wanted))
        else:
            failures += 1
            print("FAIL  %s: wanted %s, got %s" % (rel, wanted, got))

    silent = [rule for rule in RULES if rule not in fired]
    if silent:
        failures += 1
        print("FAIL  no case shows these rules firing: %s" % ", ".join(silent))
    print()
    total = len(cases) + len(paths) + 1
    if failures:
        print("%d of %d self-test checks failed" % (failures, total))
        return 1
    print("all %d self-test checks passed" % total)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
